// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray encodedMessage;
        }

        public static unsafe _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 16) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 16) " +
                    "for command with ID 36");
            }

            var orig = new _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe();
            var comp = (Interop*)data;
            orig.encodedMessage = new byte[comp->encodedMessage.Length]; Marshal.Copy((System.IntPtr)comp->encodedMessage.Data, orig.encodedMessage, 0, (int)comp->encodedMessage.Length);
            return orig;
        }

        public System.Byte[] encodedMessage;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 36;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe(
        Entity entity,
        System.Byte[] encodedMessage
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.Other;
            Sender = 0;
            
            this.encodedMessage = encodedMessage; 
        }
        
        public static void Serialize(_cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteBytesList(commandData.encodedMessage);
        }
        
        public static _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataencodedMessage = bitStream.ReadBytesList();
    
            return new _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe()
            {
                Entity = entity,
                Routing = target,
                encodedMessage = dataencodedMessage
            };   
        }
    }

}
