// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Byte newState;
        }

        public static unsafe _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 1) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 1) " +
                    "for command with ID 38");
            }

            var orig = new _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d();
            var comp = (Interop*)data;
            orig.newState = comp->newState != 0;
            return orig;
        }

        public System.Boolean newState;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 38;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d(
        Entity entity,
        System.Boolean newState
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.AuthorityOnly;
            Sender = 0;
            
            this.newState = newState; 
        }
        
        public static void Serialize(_ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteBool(commandData.newState);
        }
        
        public static _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datanewState = bitStream.ReadBool();
    
            return new _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d()
            {
                Entity = entity,
                Routing = target,
                newState = datanewState
            };   
        }
    }

}
