// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using System.Collections.Generic;
    using UnityEngine;

    public struct Campchair_91ccee2338d92624a8021fda1c91e47c_91ccee2338d92624a8021fda1c91e47c_da4067b1_fcd3_4e8a_93ae_914a3b0df2f9 : IEntityCommand
    {
        public System.Boolean newBusyState;
        
        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 11;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public Campchair_91ccee2338d92624a8021fda1c91e47c_91ccee2338d92624a8021fda1c91e47c_da4067b1_fcd3_4e8a_93ae_914a3b0df2f9(
        Entity entity,
        System.Boolean newBusyState
)
        {
            Entity = entity;
            Routing = MessageTarget.AuthorityOnly;
            Sender = 0;
            
            this.newBusyState = newBusyState; 
        }
        
        public static void Serialize(Campchair_91ccee2338d92624a8021fda1c91e47c_91ccee2338d92624a8021fda1c91e47c_da4067b1_fcd3_4e8a_93ae_914a3b0df2f9 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteBool(commandData.newBusyState);
        }
        
        public static Campchair_91ccee2338d92624a8021fda1c91e47c_91ccee2338d92624a8021fda1c91e47c_da4067b1_fcd3_4e8a_93ae_914a3b0df2f9 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datanewBusyState = bitStream.ReadBool();
    
            return new Campchair_91ccee2338d92624a8021fda1c91e47c_91ccee2338d92624a8021fda1c91e47c_da4067b1_fcd3_4e8a_93ae_914a3b0df2f9()
            {
                Entity = entity,
                Routing = target,
                newBusyState = datanewBusyState
            };   
        }
    }

}