// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using System.Collections.Generic;
    using UnityEngine;

    public struct Campfire_3889a458e94666d4784df30d8dd06d7d_3889a458e94666d4784df30d8dd06d7d_f8f688eb_08cb_493f_acb6_d766417377d4 : IEntityCommand
    {
        public System.String syncConfigID;
        
        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 15;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public Campfire_3889a458e94666d4784df30d8dd06d7d_3889a458e94666d4784df30d8dd06d7d_f8f688eb_08cb_493f_acb6_d766417377d4(
        Entity entity,
        System.String syncConfigID
)
        {
            Entity = entity;
            Routing = MessageTarget.AuthorityOnly;
            Sender = 0;
            
            this.syncConfigID = syncConfigID; 
        }
        
        public static void Serialize(Campfire_3889a458e94666d4784df30d8dd06d7d_3889a458e94666d4784df30d8dd06d7d_f8f688eb_08cb_493f_acb6_d766417377d4 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteShortString(commandData.syncConfigID);
        }
        
        public static Campfire_3889a458e94666d4784df30d8dd06d7d_3889a458e94666d4784df30d8dd06d7d_f8f688eb_08cb_493f_acb6_d766417377d4 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datasyncConfigID = bitStream.ReadShortString();
    
            return new Campfire_3889a458e94666d4784df30d8dd06d7d_3889a458e94666d4784df30d8dd06d7d_f8f688eb_08cb_493f_acb6_d766417377d4()
            {
                Entity = entity,
                Routing = target,
                syncConfigID = datasyncConfigID
            };   
        }
    }

}