// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_35fe21b9614149b48553511c0683c2f9 : IntBinding
    {   
        private global::CosmeticsChanger CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::CosmeticsChanger)UnityComponent;
        }

        public override uint CoherenceComponentID => 52;
        public override int FieldIndex => 0;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.currentBackpack); }
            set { CastedUnityComponent.currentBackpack = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_9730620f6eb44d01b04e80e5fc5e4856 : IntBinding
    {   
        private global::CosmeticsChanger CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::CosmeticsChanger)UnityComponent;
        }

        public override uint CoherenceComponentID => 52;
        public override int FieldIndex => 1;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.currentSkinTone); }
            set { CastedUnityComponent.currentSkinTone = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(1);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(1);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_6c9facfb02c7402492da2e6e9e51ae3e : IntBinding
    {   
        private global::CosmeticsChanger CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::CosmeticsChanger)UnityComponent;
        }

        public override uint CoherenceComponentID => 52;
        public override int FieldIndex => 2;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.currentClothes); }
            set { CastedUnityComponent.currentClothes = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(2);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(2);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_665a00acfb6d46d0a9e9276e9681a4ff : IntBinding
    {   
        private global::CosmeticsChanger CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::CosmeticsChanger)UnityComponent;
        }

        public override uint CoherenceComponentID => 52;
        public override int FieldIndex => 3;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.currentBody); }
            set { CastedUnityComponent.currentBody = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(3);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(3);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_afb54d316be244a890e58fd53680e2d4 : IntBinding
    {   
        private global::CosmeticsChanger CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::CosmeticsChanger)UnityComponent;
        }

        public override uint CoherenceComponentID => 52;
        public override int FieldIndex => 4;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.currentHairstyle); }
            set { CastedUnityComponent.currentHairstyle = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(4);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(4);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_4d9a62442a074534bca027258cca3b8c : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_60b57dc105e34765bb249dbf96b35ed4 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 1;
        public override int FieldIndex => 0;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetQuaternion().ToUnityQuaternion();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetQuaternion(Value.ToCoreQuaternion());
            }
            else
            {
                field.SetQuaternion(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToCoreQuaternion());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_9d071ea42a6e41dc955438febad4d202 : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 17;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_2ffecec9e60b43ea89f0a6e4bd8598b3 : StringBinding
    {   
        private global::TMPro.TextMeshProUGUI CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::TMPro.TextMeshProUGUI)UnityComponent;
        }

        public override uint CoherenceComponentID => 49;
        public override int FieldIndex => 0;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.text); }
            set { CastedUnityComponent.text = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetString();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetString(Value);
            }
            else
            {
                field.SetString(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_e1e87976a62a499c9c88381bbdde8ec3 : DeepPositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 51;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
            set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_b6102148731e46228baec06b4dd806c0 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override uint CoherenceComponentID => 48;
        public override int FieldIndex => 0;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetFloat();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetFloat(Value);
            }
            else
            {
                field.SetFloat(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_779cfe66b4254a8089f517a1867b19aa : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override uint CoherenceComponentID => 48;
        public override int FieldIndex => 1;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(1);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(1);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_787a2c4d82f44358ba8da3ebd14885aa : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override uint CoherenceComponentID => 48;
        public override int FieldIndex => 2;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(2);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(2);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_3cfde6644c5b46d69583102fdb4ad3d0 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override uint CoherenceComponentID => 48;
        public override int FieldIndex => 3;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(3);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(3);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_2c2f3f51b6a9480aa62ab1a234005a23 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override uint CoherenceComponentID => 48;
        public override int FieldIndex => 4;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(4);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(4);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_6529ec93596b48d8a68a785189a35e85 : StringBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override uint CoherenceComponentID => 50;
        public override int FieldIndex => 0;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.path); }
            set { CastedUnityComponent.path = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetString();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetString(Value);
            }
            else
            {
                field.SetString(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_cd9bcc1feead9419fac0c5981ce85c23_94d662d5ece44c27a4979d590435d027 : IntBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override uint CoherenceComponentID => 50;
        public override int FieldIndex => 1;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.pathDirtyCounter); }
            set { CastedUnityComponent.pathDirtyCounter = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(1);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(1);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_cd9bcc1feead9419fac0c5981ce85c23 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_cd9bcc1feead9419fac0c5981ce85c23>();
        
        private global::UnityEngine.Animator _cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6_CommandTarget;
        private global::ChopAction _cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8_CommandTarget;
        private global::SitAction _cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142_CommandTarget;
        private global::Emotes _cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d_CommandTarget;
        private global::Emotes _cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c_CommandTarget;
        private global::Emotes _cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829_CommandTarget;
        private global::GrabAction _cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41_CommandTarget;
        private global::GrabAction _cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5_CommandTarget;
        private global::Chat _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["35fe21b9614149b48553511c0683c2f9"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_35fe21b9614149b48553511c0683c2f9(),
			["9730620f6eb44d01b04e80e5fc5e4856"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_9730620f6eb44d01b04e80e5fc5e4856(),
			["6c9facfb02c7402492da2e6e9e51ae3e"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_6c9facfb02c7402492da2e6e9e51ae3e(),
			["665a00acfb6d46d0a9e9276e9681a4ff"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_665a00acfb6d46d0a9e9276e9681a4ff(),
			["afb54d316be244a890e58fd53680e2d4"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_afb54d316be244a890e58fd53680e2d4(),
			["4d9a62442a074534bca027258cca3b8c"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_4d9a62442a074534bca027258cca3b8c(),
			["60b57dc105e34765bb249dbf96b35ed4"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_60b57dc105e34765bb249dbf96b35ed4(),
			["9d071ea42a6e41dc955438febad4d202"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_9d071ea42a6e41dc955438febad4d202(),
			["2ffecec9e60b43ea89f0a6e4bd8598b3"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_2ffecec9e60b43ea89f0a6e4bd8598b3(),
			["e1e87976a62a499c9c88381bbdde8ec3"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_e1e87976a62a499c9c88381bbdde8ec3(),
			["b6102148731e46228baec06b4dd806c0"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_b6102148731e46228baec06b4dd806c0(),
			["779cfe66b4254a8089f517a1867b19aa"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_779cfe66b4254a8089f517a1867b19aa(),
			["787a2c4d82f44358ba8da3ebd14885aa"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_787a2c4d82f44358ba8da3ebd14885aa(),
			["3cfde6644c5b46d69583102fdb4ad3d0"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_3cfde6644c5b46d69583102fdb4ad3d0(),
			["2c2f3f51b6a9480aa62ab1a234005a23"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_2c2f3f51b6a9480aa62ab1a234005a23(),
			["6529ec93596b48d8a68a785189a35e85"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_6529ec93596b48d8a68a785189a35e85(),
			["94d662d5ece44c27a4979d590435d027"] = new Binding_cd9bcc1feead9419fac0c5981ce85c23_94d662d5ece44c27a4979d590435d027(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_cd9bcc1feead9419fac0c5981ce85c23()
        {
            bakedCommandBindings.Add("3f725e0b03bc47c6b9a9e726699545a6", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6);
            bakedCommandBindings.Add("9072e96068c94ef9a783ea24d7448bf8", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8);
            bakedCommandBindings.Add("9b336114382d4c8e917671bfe4a6a142", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142);
            bakedCommandBindings.Add("a6362094f44f4918a0b4a6b21f19b61d", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d);
            bakedCommandBindings.Add("c6cd65f2d33547e7800e9cd24ce9a96c", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c);
            bakedCommandBindings.Add("344741bcfef14e43909a3d3fe59aa829", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829);
            bakedCommandBindings.Add("2306915e22844eadbded8e81dad23c41", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41);
            bakedCommandBindings.Add("a44176edbb6f4de88cf611e02b9b81a5", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5);
            bakedCommandBindings.Add("d80a9015b8844731b2e04870faa56abe", BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6_CommandTarget = (global::UnityEngine.Animator)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6_localTarget = (global::UnityEngine.Animator)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"UnityEngine.Animator.SetTrigger",
            	"(System.String)",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6(__args, _cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6_localTarget),
            	MessageTarget.All,
            	_cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(29, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);

            command.GetField(0).SetString(((System.String)requestArgs.Args[0]));

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6(GenericCommandRequestArgs requestArgs, global::UnityEngine.Animator target)
        {
			target.SetTrigger((global::System.String)(requestArgs.Args[0]));
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6_CommandTarget;

            var arg0 = (System.String)(command.GetField(0).GetString());

            command.Dispose();

			target.SetTrigger(arg0);
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8_CommandTarget = (global::ChopAction)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8_localTarget = (global::ChopAction)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"ChopAction.PlayChopSound",
            	"()",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8(__args, _cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8_localTarget),
            	MessageTarget.Other,
            	_cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(30, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8(GenericCommandRequestArgs requestArgs, global::ChopAction target)
        {
			target.PlayChopSound();
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8_CommandTarget;


            command.Dispose();

			target.PlayChopSound();
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142_CommandTarget = (global::SitAction)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142_localTarget = (global::SitAction)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"SitAction.PlaySitSound",
            	"()",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142(__args, _cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142_localTarget),
            	MessageTarget.Other,
            	_cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(31, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142(GenericCommandRequestArgs requestArgs, global::SitAction target)
        {
			target.PlaySitSound();
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142_CommandTarget;


            command.Dispose();

			target.PlaySitSound();
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d_CommandTarget = (global::Emotes)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d_localTarget = (global::Emotes)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Emotes.PlayYesSound",
            	"()",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d(__args, _cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d_localTarget),
            	MessageTarget.All,
            	_cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(33, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d(GenericCommandRequestArgs requestArgs, global::Emotes target)
        {
			target.PlayYesSound();
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d_CommandTarget;


            command.Dispose();

			target.PlayYesSound();
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c_CommandTarget = (global::Emotes)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c_localTarget = (global::Emotes)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Emotes.PlayNoSound",
            	"()",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c(__args, _cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c_localTarget),
            	MessageTarget.All,
            	_cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(34, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c(GenericCommandRequestArgs requestArgs, global::Emotes target)
        {
			target.PlayNoSound();
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c_CommandTarget;


            command.Dispose();

			target.PlayNoSound();
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829_CommandTarget = (global::Emotes)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829_localTarget = (global::Emotes)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Emotes.PlayHeySound",
            	"()",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829(__args, _cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829_localTarget),
            	MessageTarget.All,
            	_cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(28, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829(GenericCommandRequestArgs requestArgs, global::Emotes target)
        {
			target.PlayHeySound();
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829_CommandTarget;


            command.Dispose();

			target.PlayHeySound();
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41_CommandTarget = (global::GrabAction)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41_localTarget = (global::GrabAction)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"GrabAction.PlayPickUpSound",
            	"()",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41(__args, _cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41_localTarget),
            	MessageTarget.All,
            	_cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(27, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41(GenericCommandRequestArgs requestArgs, global::GrabAction target)
        {
			target.PlayPickUpSound();
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41_CommandTarget;


            command.Dispose();

			target.PlayPickUpSound();
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5_CommandTarget = (global::GrabAction)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5_localTarget = (global::GrabAction)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"GrabAction.PlayDropSound",
            	"()",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5(__args, _cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5_localTarget),
            	MessageTarget.All,
            	_cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(32, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5(GenericCommandRequestArgs requestArgs, global::GrabAction target)
        {
			target.PlayDropSound();
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5_CommandTarget;


            command.Dispose();

			target.PlayDropSound();
        }
        private void BakeCommandBinding__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe_CommandTarget = (global::Chat)commandBinding.UnityComponent;
            var _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe_localTarget = (global::Chat)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Chat.SendChatMessage",
            	"(System.Byte[])",
            	SendCommand__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe,
            	__args => ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe(__args, _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe_localTarget),
            	MessageTarget.Other,
            	_cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(35, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);

            command.GetField(0).SetBytes(((System.Byte[])requestArgs.Args[0]));

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe(GenericCommandRequestArgs requestArgs, global::Chat target)
        {
			target.SendChatMessage((global::System.Byte[])(requestArgs.Args[0]));
        }

        private void ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe(CommandData command)
        {
			var target = _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe_CommandTarget;

            var arg0 = (System.Byte[])(command.GetField(0).GetBytes());

            command.Dispose();

			target.SendChatMessage(arg0);
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                case 29:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6(command);
                    break;
                case 30:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8(command);
                    break;
                case 31:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142(command);
                    break;
                case 33:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d(command);
                    break;
                case 34:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c(command);
                    break;
                case 28:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829(command);
                    break;
                case 27:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41(command);
                    break;
                case 32:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5(command);
                    break;
                case 35:
                    ReceiveCommand__cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe(command);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_cd9bcc1feead9419fac0c5981ce85c23 Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_cd9bcc1feead9419fac0c5981ce85c23>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
