// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_3d92447627afdfc419ceeb6b26251a87_22b719ee_1f9c_41de_9e3e_c27a05a413a8 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override UnityEngine.Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }
            
            return value;
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
        {
            var update = (WorldPosition)coherenceComponent;
            if (RuntimeInterpolationSettings.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(time);
            }
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_3d92447627afdfc419ceeb6b26251a87_a947e129_13b6_4796_ae92_4a538e3de89b : IntBinding
    {   
        private global::ChoppableTree CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::ChoppableTree)UnityComponent;
        }

        public override string CoherenceComponentName => "Tree_3d92447627afdfc419ceeb6b26251a87_ChoppableTree_1406947345458511524";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.energy); }
            set { CastedUnityComponent.energy = (System.Int32)(value); }
        }

        protected override System.Int32 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((Tree_3d92447627afdfc419ceeb6b26251a87_ChoppableTree_1406947345458511524)coherenceComponent).energy;
            
            return value;
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
        {
            var update = (Tree_3d92447627afdfc419ceeb6b26251a87_ChoppableTree_1406947345458511524)coherenceComponent;
            if (RuntimeInterpolationSettings.IsInterpolationNone)
            {
                update.energy = Value;
            }
            else
            {
                update.energy = GetInterpolatedAt(time);
            }
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new Tree_3d92447627afdfc419ceeb6b26251a87_ChoppableTree_1406947345458511524();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSyncTree_3d92447627afdfc419ceeb6b26251a87 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSyncTree_3d92447627afdfc419ceeb6b26251a87>();
        
        private global::ChoppableTree Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6_CommandTarget;
        private global::ChoppableTree Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7_CommandTarget;
        private global::ChoppableTree Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["22b719ee-1f9c-41de-9e3e-c27a05a413a8"] = new Binding_3d92447627afdfc419ceeb6b26251a87_22b719ee_1f9c_41de_9e3e_c27a05a413a8(),
            ["a947e129-13b6-4796-ae92-4a538e3de89b"] = new Binding_3d92447627afdfc419ceeb6b26251a87_a947e129_13b6_4796_ae92_4a538e3de89b(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSyncTree_3d92447627afdfc419ceeb6b26251a87()
        {
            bakedCommandBindings.Add("e5df7db2-535f-4106-90ed-f553148f2ac6", BakeCommandBinding_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6);
            bakedCommandBindings.Add("64674b8d-4999-426f-b995-493ab95cb6d7", BakeCommandBinding_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7);
            bakedCommandBindings.Add("195171a3-094b-49ce-9dc6-24b38e8a6b09", BakeCommandBinding_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6_CommandTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("ChoppableTree.Chop", "()", SendCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6, ReceiveLocalCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6, MessageTarget.AuthorityOnly, Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6_CommandTarget, false);
        }
        
        private void SendCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6(MessageTarget target, object[] args)
        {
            var command = new Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6(MessageTarget target, object[] args)
        {
            var command = new Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6();
            
            
            ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6(command);
        }

        private void ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6(Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6 command)
        {
            var target = Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6_CommandTarget;
            
            target.Chop();
        }
    
        private void BakeCommandBinding_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7_CommandTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("ChoppableTree.ChangeState", "(System.Boolean)", SendCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7, ReceiveLocalCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7, MessageTarget.Other, Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7_CommandTarget, false);
        }
        
        private void SendCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7(MessageTarget target, object[] args)
        {
            var command = new Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7();
            
            int i = 0;
            command.toUp = (System.Boolean)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7(MessageTarget target, object[] args)
        {
            var command = new Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7();
            
            int i = 0;
            command.toUp = (System.Boolean)args[i++];
            
            ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7(command);
        }

        private void ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7(Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7 command)
        {
            var target = Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7_CommandTarget;
            
            target.ChangeState((System.Boolean)(command.toUp));
        }
    
        private void BakeCommandBinding_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09_CommandTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("ChoppableTree.PlayChopEffect", "()", SendCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09, ReceiveLocalCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09, MessageTarget.Other, Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09_CommandTarget, false);
        }
        
        private void SendCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09(MessageTarget target, object[] args)
        {
            var command = new Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09(MessageTarget target, object[] args)
        {
            var command = new Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09();
            
            
            ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09(command);
        }

        private void ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09(Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09 command)
        {
            var target = Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09_CommandTarget;
            
            target.PlayChopEffect();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6 castedCommand:
                    ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_e5df7db2_535f_4106_90ed_f553148f2ac6(castedCommand);
                    break;
                case Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7 castedCommand:
                    ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_64674b8d_4999_426f_b995_493ab95cb6d7(castedCommand);
                    break;
                case Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09 castedCommand:
                    ReceiveCommand_Tree_3d92447627afdfc419ceeb6b26251a87_3d92447627afdfc419ceeb6b26251a87_195171a3_094b_49ce_9dc6_24b38e8a6b09(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSyncTree_3d92447627afdfc419ceeb6b26251a87 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSyncTree_3d92447627afdfc419ceeb6b26251a87>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}