// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_91ccee2338d92624a8021fda1c91e47c_af57f962994c4ec7887c2f2f6b67f68a : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_91ccee2338d92624a8021fda1c91e47c_6653d280b1864071bb3815f49a73d029 : BoolBinding
    {   
        private global::Chair CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Chair)UnityComponent;
        }

        public override uint CoherenceComponentID => 40;
        public override int FieldIndex => 0;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBusy); }
            set { CastedUnityComponent.isBusy = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_91ccee2338d92624a8021fda1c91e47c_85ff4db8c33a45dfab7139834053c3e6 : BoolBinding
    {   
        private global::UnityEngine.CapsuleCollider CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.CapsuleCollider)UnityComponent;
        }

        public override uint CoherenceComponentID => 39;
        public override int FieldIndex => 0;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_91ccee2338d92624a8021fda1c91e47c : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_91ccee2338d92624a8021fda1c91e47c>();
        
        private global::Chair _91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["af57f962994c4ec7887c2f2f6b67f68a"] = new Binding_91ccee2338d92624a8021fda1c91e47c_af57f962994c4ec7887c2f2f6b67f68a(),
			["6653d280b1864071bb3815f49a73d029"] = new Binding_91ccee2338d92624a8021fda1c91e47c_6653d280b1864071bb3815f49a73d029(),
			["85ff4db8c33a45dfab7139834053c3e6"] = new Binding_91ccee2338d92624a8021fda1c91e47c_85ff4db8c33a45dfab7139834053c3e6(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_91ccee2338d92624a8021fda1c91e47c()
        {
            bakedCommandBindings.Add("da4067b1fcd34e8a93ae914a3b0df2f9", BakeCommandBinding__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9_CommandTarget = (global::Chair)commandBinding.UnityComponent;
            var _91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9_localTarget = (global::Chair)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Chair.ChangeState",
            	"(System.Boolean)",
            	SendCommand__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9,
            	__args => ReceiveLocalCommand__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9(__args, _91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9_localTarget),
            	MessageTarget.StateAuthorityOnly,
            	_91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(20, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);

            command.GetField(0).SetBool(((System.Boolean)requestArgs.Args[0]));

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9(GenericCommandRequestArgs requestArgs, global::Chair target)
        {
			target.ChangeState((global::System.Boolean)(requestArgs.Args[0]));
        }

        private void ReceiveCommand__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9(CommandData command)
        {
			var target = _91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9_CommandTarget;

            var arg0 = (System.Boolean)(command.GetField(0).GetBool());

            command.Dispose();

			target.ChangeState(arg0);
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                case 20:
                    ReceiveCommand__91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9(command);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_91ccee2338d92624a8021fda1c91e47c Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_91ccee2338d92624a8021fda1c91e47c>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
