// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_7eef8177eb732314fb850470094a70c9_3c6dd2a1004a48f9882846782165be86 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_7eef8177eb732314fb850470094a70c9_8f5fdae3bab74f309565b69548451c75 : BoolBinding
    {   
        private global::Chair CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Chair)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_7eef8177eb732314fb850470094a70c9_468635232);
        public override string CoherenceComponentName => "_7eef8177eb732314fb850470094a70c9_468635232";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBusy); }
            set { CastedUnityComponent.isBusy = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_7eef8177eb732314fb850470094a70c9_468635232)coherenceComponent).isBusy;

            var simFrame = ((_7eef8177eb732314fb850470094a70c9_468635232)coherenceComponent).isBusySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_7eef8177eb732314fb850470094a70c9_468635232)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.isBusy = Value;
            }
            else
            {
                update.isBusy = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBusySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _7eef8177eb732314fb850470094a70c9_468635232();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_7eef8177eb732314fb850470094a70c9_96deafb267de4576b43f8958e112ee4d : BoolBinding
    {   
        private global::UnityEngine.CapsuleCollider CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.CapsuleCollider)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_7eef8177eb732314fb850470094a70c9_468635231);
        public override string CoherenceComponentName => "_7eef8177eb732314fb850470094a70c9_468635231";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_7eef8177eb732314fb850470094a70c9_468635231)coherenceComponent).enabled;

            var simFrame = ((_7eef8177eb732314fb850470094a70c9_468635231)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_7eef8177eb732314fb850470094a70c9_468635231)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _7eef8177eb732314fb850470094a70c9_468635231();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_7eef8177eb732314fb850470094a70c9 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_7eef8177eb732314fb850470094a70c9>();
        
        private global::Chair _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["3c6dd2a1004a48f9882846782165be86"] = new Binding_7eef8177eb732314fb850470094a70c9_3c6dd2a1004a48f9882846782165be86(),
            ["8f5fdae3bab74f309565b69548451c75"] = new Binding_7eef8177eb732314fb850470094a70c9_8f5fdae3bab74f309565b69548451c75(),
            ["96deafb267de4576b43f8958e112ee4d"] = new Binding_7eef8177eb732314fb850470094a70c9_96deafb267de4576b43f8958e112ee4d(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_7eef8177eb732314fb850470094a70c9()
        {
            bakedCommandBindings.Add("510b1c05cf0249e68fbcff362acff187", BakeCommandBinding__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_CommandTarget = (global::Chair)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Chair.ChangeState", "(System.Boolean)", SendCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187, ReceiveLocalCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187, MessageTarget.AuthorityOnly, _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_CommandTarget, false);
        }
        
        private void SendCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187();
            
            int i = 0;
            command.newBusyState = (System.Boolean)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187();
            
            int i = 0;
            command.newBusyState = (System.Boolean)args[i++];
            
            ReceiveCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(command);
        }

        private void ReceiveCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(_7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187 command)
        {
            var target = _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_CommandTarget;
            
            target.ChangeState((System.Boolean)(command.newBusyState));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187 castedCommand:
                    ReceiveCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_7eef8177eb732314fb850470094a70c9 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_7eef8177eb732314fb850470094a70c9>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
