// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_3889a458e94666d4784df30d8dd06d7d_05ba497e2c7b4bf99d98348ae880439b : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_3889a458e94666d4784df30d8dd06d7d_3d7b0de09c2348ebabdb8c4aa943ce3b : IntBinding
    {   
        private global::Campfire CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Campfire)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3889a458e94666d4784df30d8dd06d7d_6540142254599110064);
        public override string CoherenceComponentName => "_3889a458e94666d4784df30d8dd06d7d_6540142254599110064";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.activeFireEffect); }
            set { CastedUnityComponent.activeFireEffect = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent).activeFireEffect;

            var simFrame = ((_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent).activeFireEffectSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.activeFireEffect = Value;
            }
            else
            {
                update.activeFireEffect = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.activeFireEffectSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3889a458e94666d4784df30d8dd06d7d_6540142254599110064();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_3889a458e94666d4784df30d8dd06d7d_f16a85076b0d47e8872375cb715fc67e : FloatBinding
    {   
        private global::Campfire CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Campfire)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3889a458e94666d4784df30d8dd06d7d_6540142254599110064);
        public override string CoherenceComponentName => "_3889a458e94666d4784df30d8dd06d7d_6540142254599110064";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.fireTimer); }
            set { CastedUnityComponent.fireTimer = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent).fireTimer;

            var simFrame = ((_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent).fireTimerSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.fireTimer = Value;
            }
            else
            {
                update.fireTimer = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.fireTimerSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3889a458e94666d4784df30d8dd06d7d_6540142254599110064();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_3889a458e94666d4784df30d8dd06d7d_d8d012f4196145caa10c8e40b2bd3e06 : FloatBinding
    {   
        private global::Campfire CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Campfire)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3889a458e94666d4784df30d8dd06d7d_6540142254599110064);
        public override string CoherenceComponentName => "_3889a458e94666d4784df30d8dd06d7d_6540142254599110064";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.bigFireTimer); }
            set { CastedUnityComponent.bigFireTimer = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent).bigFireTimer;

            var simFrame = ((_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent).bigFireTimerSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.bigFireTimer = Value;
            }
            else
            {
                update.bigFireTimer = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.bigFireTimerSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3889a458e94666d4784df30d8dd06d7d_6540142254599110064();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_3889a458e94666d4784df30d8dd06d7d : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_3889a458e94666d4784df30d8dd06d7d>();
        
        private global::Campfire _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db_CommandTarget;
        private global::Campfire _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4_CommandTarget;
        private global::Campfire _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38_CommandTarget;
        private global::Campfire _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["05ba497e2c7b4bf99d98348ae880439b"] = new Binding_3889a458e94666d4784df30d8dd06d7d_05ba497e2c7b4bf99d98348ae880439b(),
            ["3d7b0de09c2348ebabdb8c4aa943ce3b"] = new Binding_3889a458e94666d4784df30d8dd06d7d_3d7b0de09c2348ebabdb8c4aa943ce3b(),
            ["f16a85076b0d47e8872375cb715fc67e"] = new Binding_3889a458e94666d4784df30d8dd06d7d_f16a85076b0d47e8872375cb715fc67e(),
            ["d8d012f4196145caa10c8e40b2bd3e06"] = new Binding_3889a458e94666d4784df30d8dd06d7d_d8d012f4196145caa10c8e40b2bd3e06(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_3889a458e94666d4784df30d8dd06d7d()
        {
            bakedCommandBindings.Add("3738e04300d846dfa774ba252d8208db", BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db);
            bakedCommandBindings.Add("f8f688eb08cb493facb6d766417377d4", BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4);
            bakedCommandBindings.Add("3664e59fd3cd4dd28175902369f5bb38", BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38);
            bakedCommandBindings.Add("df8fe4d8a6104b7ab780e439afba5391", BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db_CommandTarget = (global::Campfire)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Campfire.PlayInstantEffects", "()", SendCommand__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db, ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db, MessageTarget.All, _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db_CommandTarget, false);
        }
        
        private void SendCommand__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db();
            
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db();
            
            
            ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db(command);
        }

        private void ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db(_3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db command)
        {
            var target = _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db_CommandTarget;
            
            target.PlayInstantEffects();
        }
    
        private void BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4_CommandTarget = (global::Campfire)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Campfire.BurnObject", "(System.String)", SendCommand__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4, ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4, MessageTarget.AuthorityOnly, _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4_CommandTarget, false);
        }
        
        private void SendCommand__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4();
            
            int i = 0;
            command.syncConfigID = (System.String)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4();
            
            int i = 0;
            command.syncConfigID = (System.String)args[i++];
            
            ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4(command);
        }

        private void ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4(_3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4 command)
        {
            var target = _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4_CommandTarget;
            
            target.BurnObject((System.String)(command.syncConfigID));
        }
    
        private void BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38_CommandTarget = (global::Campfire)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Campfire.FireDiedDown", "(System.Int32System.Int32)", SendCommand__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38, ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38, MessageTarget.All, _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38_CommandTarget, false);
        }
        
        private void SendCommand__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38();
            
            int i = 0;
            command.oldEffectID = (System.Int32)args[i++];
            command.newEffectID = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38();
            
            int i = 0;
            command.oldEffectID = (System.Int32)args[i++];
            command.newEffectID = (System.Int32)args[i++];
            
            ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38(command);
        }

        private void ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38(_3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38 command)
        {
            var target = _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38_CommandTarget;
            
            target.FireDiedDown((System.Int32)(command.oldEffectID),(System.Int32)(command.newEffectID));
        }
    
        private void BakeCommandBinding__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391_CommandTarget = (global::Campfire)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Campfire.FireStateChanged", "(System.Int32System.Int32System.String)", SendCommand__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391, ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391, MessageTarget.All, _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391_CommandTarget, false);
        }
        
        private void SendCommand__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391();
            
            int i = 0;
            command.oldEffectID = (System.Int32)args[i++];
            command.newEffectID = (System.Int32)args[i++];
            command.syncConfigID = (System.String)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391();
            
            int i = 0;
            command.oldEffectID = (System.Int32)args[i++];
            command.newEffectID = (System.Int32)args[i++];
            command.syncConfigID = (System.String)args[i++];
            
            ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391(command);
        }

        private void ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391(_3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391 command)
        {
            var target = _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391_CommandTarget;
            
            target.FireStateChanged((System.Int32)(command.oldEffectID),(System.Int32)(command.newEffectID),(System.String)(command.syncConfigID));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db castedCommand:
                    ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db(castedCommand);
                    break;
                case _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4 castedCommand:
                    ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4(castedCommand);
                    break;
                case _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38 castedCommand:
                    ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38(castedCommand);
                    break;
                case _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391 castedCommand:
                    ReceiveCommand__3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_3889a458e94666d4784df30d8dd06d7d Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_3889a458e94666d4784df30d8dd06d7d>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
