// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_7eef8177eb732314fb850470094a70c9_3c6dd2a1004a48f9882846782165be86 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_7eef8177eb732314fb850470094a70c9_8f5fdae3bab74f309565b69548451c75 : BoolBinding
    {   
        private global::Chair CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Chair)UnityComponent;
        }

        public override uint CoherenceComponentID => 32;
        public override int FieldIndex => 0;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBusy); }
            set { CastedUnityComponent.isBusy = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_7eef8177eb732314fb850470094a70c9_96deafb267de4576b43f8958e112ee4d : BoolBinding
    {   
        private global::UnityEngine.CapsuleCollider CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.CapsuleCollider)UnityComponent;
        }

        public override uint CoherenceComponentID => 31;
        public override int FieldIndex => 0;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_7eef8177eb732314fb850470094a70c9 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_7eef8177eb732314fb850470094a70c9>();
        
        private global::Chair _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["3c6dd2a1004a48f9882846782165be86"] = new Binding_7eef8177eb732314fb850470094a70c9_3c6dd2a1004a48f9882846782165be86(),
			["8f5fdae3bab74f309565b69548451c75"] = new Binding_7eef8177eb732314fb850470094a70c9_8f5fdae3bab74f309565b69548451c75(),
			["96deafb267de4576b43f8958e112ee4d"] = new Binding_7eef8177eb732314fb850470094a70c9_96deafb267de4576b43f8958e112ee4d(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_7eef8177eb732314fb850470094a70c9()
        {
            bakedCommandBindings.Add("510b1c05cf0249e68fbcff362acff187", BakeCommandBinding__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_CommandTarget = (global::Chair)commandBinding.UnityComponent;
            var _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_localTarget = (global::Chair)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Chair.ChangeState",
            	"(System.Boolean)",
            	SendCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187,
            	__args => ReceiveLocalCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(__args, _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_localTarget),
            	MessageTarget.StateAuthorityOnly,
            	_7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(17, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);

            command.GetField(0).SetBool(((System.Boolean)requestArgs.Args[0]));

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(GenericCommandRequestArgs requestArgs, global::Chair target)
        {
			target.ChangeState((global::System.Boolean)(requestArgs.Args[0]));
        }

        private void ReceiveCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(CommandData command)
        {
			var target = _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187_CommandTarget;

            var arg0 = (System.Boolean)(command.GetField(0).GetBool());

            command.Dispose();

			target.ChangeState(arg0);
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                case 17:
                    ReceiveCommand__7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187(command);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_7eef8177eb732314fb850470094a70c9 Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_7eef8177eb732314fb850470094a70c9>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
