// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_aa3341ec45d847e3a6334d365bb6e8f6 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_4cef7f16f6344b529a98ff11487873bc : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 1;
        public override int FieldIndex => 0;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetQuaternion().ToUnityQuaternion();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetQuaternion(Value.ToCoreQuaternion());
            }
            else
            {
                field.SetQuaternion(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToCoreQuaternion());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_f4b199dae036494baf4943dea2b97d33 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override uint CoherenceComponentID => 43;
        public override int FieldIndex => 0;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_5735b03a1aa74d87a5f2e163eed89df2 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override uint CoherenceComponentID => 43;
        public override int FieldIndex => 1;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(1);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(1);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_0174ef8a52ab48e6aee788bea243f7f5 : BoolBinding
    {   
        private global::Chair CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Chair)UnityComponent;
        }

        public override uint CoherenceComponentID => 45;
        public override int FieldIndex => 0;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBusy); }
            set { CastedUnityComponent.isBusy = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_7bdbd9a8685a4f6d9ca68b99e9a541fc : FloatBinding
    {   
        private global::KeeperRobot CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::KeeperRobot)UnityComponent;
        }

        public override uint CoherenceComponentID => 44;
        public override int FieldIndex => 0;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.situationCheckCooldown); }
            set { CastedUnityComponent.situationCheckCooldown = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetFloat();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetFloat(Value);
            }
            else
            {
                field.SetFloat(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_191f016e9e1247d1a2d360eef5cf9d84 : EnumBinding
    {   
        private global::KeeperRobot CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::KeeperRobot)UnityComponent;
        }

        public override uint CoherenceComponentID => 44;
        public override int FieldIndex => 1;

        public override System.Int32 Value
        {
            get { return (System.Int32)CastedUnityComponent._state; }
            set { CastedUnityComponent._state = (KeeperRobot.RobotState)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(1);
            
            var value = field.GetEnum();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(1);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetEnum(Value);
            }
            else
            {
                field.SetEnum(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a857fd6c221f7f04fa9ed500e317642a_2f0354a9115a494d84c4173b43993356 : BoolBinding
    {   
        private global::KeeperRobot CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::KeeperRobot)UnityComponent;
        }

        public override uint CoherenceComponentID => 44;
        public override int FieldIndex => 2;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(2);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(2);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_a857fd6c221f7f04fa9ed500e317642a : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_a857fd6c221f7f04fa9ed500e317642a>();
        
        private global::Chair _a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4_CommandTarget;
        private global::KeeperRobot _a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199_CommandTarget;
        private global::KeeperRobot _a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8_CommandTarget;
        private global::KeeperRobot _a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e_CommandTarget;
        private global::KeeperRobot _a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["aa3341ec45d847e3a6334d365bb6e8f6"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_aa3341ec45d847e3a6334d365bb6e8f6(),
			["4cef7f16f6344b529a98ff11487873bc"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_4cef7f16f6344b529a98ff11487873bc(),
			["f4b199dae036494baf4943dea2b97d33"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_f4b199dae036494baf4943dea2b97d33(),
			["5735b03a1aa74d87a5f2e163eed89df2"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_5735b03a1aa74d87a5f2e163eed89df2(),
			["0174ef8a52ab48e6aee788bea243f7f5"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_0174ef8a52ab48e6aee788bea243f7f5(),
			["7bdbd9a8685a4f6d9ca68b99e9a541fc"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_7bdbd9a8685a4f6d9ca68b99e9a541fc(),
			["191f016e9e1247d1a2d360eef5cf9d84"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_191f016e9e1247d1a2d360eef5cf9d84(),
			["2f0354a9115a494d84c4173b43993356"] = new Binding_a857fd6c221f7f04fa9ed500e317642a_2f0354a9115a494d84c4173b43993356(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_a857fd6c221f7f04fa9ed500e317642a()
        {
            bakedCommandBindings.Add("7f3e0b9e3ab247f68ebb0067b5b4b6c4", BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4);
            bakedCommandBindings.Add("ab045865e78d4e8c9562d53fcea0a199", BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199);
            bakedCommandBindings.Add("efd5ed06a339416b8819ea9524e35db8", BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8);
            bakedCommandBindings.Add("eee23e58897b48f7ba844e115ca6978e", BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e);
            bakedCommandBindings.Add("d982f989b8ee4d79b39706515c828726", BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4_CommandTarget = (global::Chair)commandBinding.UnityComponent;
            var _a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4_localTarget = (global::Chair)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Chair.ChangeState",
            	"(System.Boolean)",
            	SendCommand__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4,
            	__args => ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4(__args, _a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4_localTarget),
            	MessageTarget.StateAuthorityOnly,
            	_a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(21, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);

            command.GetField(0).SetBool(((System.Boolean)requestArgs.Args[0]));

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4(GenericCommandRequestArgs requestArgs, global::Chair target)
        {
			target.ChangeState((global::System.Boolean)(requestArgs.Args[0]));
        }

        private void ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4(CommandData command)
        {
			var target = _a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4_CommandTarget;

            var arg0 = (System.Boolean)(command.GetField(0).GetBool());

            command.Dispose();

			target.ChangeState(arg0);
        }
        private void BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199_CommandTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            var _a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199_localTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"KeeperRobot.PlayHumSound",
            	"()",
            	SendCommand__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199,
            	__args => ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199(__args, _a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199_localTarget),
            	MessageTarget.All,
            	_a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(22, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199(GenericCommandRequestArgs requestArgs, global::KeeperRobot target)
        {
			target.PlayHumSound();
        }

        private void ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199(CommandData command)
        {
			var target = _a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199_CommandTarget;


            command.Dispose();

			target.PlayHumSound();
        }
        private void BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8_CommandTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            var _a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8_localTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"KeeperRobot.PlayVoiceSound",
            	"()",
            	SendCommand__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8,
            	__args => ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8(__args, _a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8_localTarget),
            	MessageTarget.All,
            	_a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(25, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8(GenericCommandRequestArgs requestArgs, global::KeeperRobot target)
        {
			target.PlayVoiceSound();
        }

        private void ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8(CommandData command)
        {
			var target = _a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8_CommandTarget;


            command.Dispose();

			target.PlayVoiceSound();
        }
        private void BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e_CommandTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            var _a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e_localTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"KeeperRobot.PlayConjure",
            	"()",
            	SendCommand__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e,
            	__args => ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e(__args, _a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e_localTarget),
            	MessageTarget.All,
            	_a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(24, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e(GenericCommandRequestArgs requestArgs, global::KeeperRobot target)
        {
			target.PlayConjure();
        }

        private void ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e(CommandData command)
        {
			var target = _a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e_CommandTarget;


            command.Dispose();

			target.PlayConjure();
        }
        private void BakeCommandBinding__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726_CommandTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            var _a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726_localTarget = (global::KeeperRobot)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"KeeperRobot.PlayAppear",
            	"()",
            	SendCommand__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726,
            	__args => ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726(__args, _a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726_localTarget),
            	MessageTarget.All,
            	_a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(23, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726(GenericCommandRequestArgs requestArgs, global::KeeperRobot target)
        {
			target.PlayAppear();
        }

        private void ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726(CommandData command)
        {
			var target = _a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726_CommandTarget;


            command.Dispose();

			target.PlayAppear();
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                case 21:
                    ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4(command);
                    break;
                case 22:
                    ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_ab045865e78d4e8c9562d53fcea0a199(command);
                    break;
                case 25:
                    ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_efd5ed06a339416b8819ea9524e35db8(command);
                    break;
                case 24:
                    ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_eee23e58897b48f7ba844e115ca6978e(command);
                    break;
                case 23:
                    ReceiveCommand__a857fd6c221f7f04fa9ed500e317642a_d982f989b8ee4d79b39706515c828726(command);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_a857fd6c221f7f04fa9ed500e317642a Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_a857fd6c221f7f04fa9ed500e317642a>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
