// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_3d92447627afdfc419ceeb6b26251a87_22b719ee1f9c41de9e3ec27a05a413a8 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_3d92447627afdfc419ceeb6b26251a87_a947e12913b64796ae924a538e3de89b : IntBinding
    {   
        private global::ChoppableTree CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::ChoppableTree)UnityComponent;
        }

        public override uint CoherenceComponentID => 25;
        public override int FieldIndex => 0;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.energy); }
            set { CastedUnityComponent.energy = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_3d92447627afdfc419ceeb6b26251a87 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_3d92447627afdfc419ceeb6b26251a87>();
        
        private global::ChoppableTree _3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6_CommandTarget;
        private global::ChoppableTree _3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca_CommandTarget;
        private global::ChoppableTree _3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["22b719ee1f9c41de9e3ec27a05a413a8"] = new Binding_3d92447627afdfc419ceeb6b26251a87_22b719ee1f9c41de9e3ec27a05a413a8(),
			["a947e12913b64796ae924a538e3de89b"] = new Binding_3d92447627afdfc419ceeb6b26251a87_a947e12913b64796ae924a538e3de89b(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_3d92447627afdfc419ceeb6b26251a87()
        {
            bakedCommandBindings.Add("e5df7db2535f410690edf553148f2ac6", BakeCommandBinding__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6);
            bakedCommandBindings.Add("d1abac12daa945619882e28463e3e3ca", BakeCommandBinding__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca);
            bakedCommandBindings.Add("4bd44a0c7fb3400db0d9719709cd4404", BakeCommandBinding__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6_CommandTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            var _3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6_localTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"ChoppableTree.Chop",
            	"()",
            	SendCommand__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6,
            	__args => ReceiveLocalCommand__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6(__args, _3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6_localTarget),
            	MessageTarget.StateAuthorityOnly,
            	_3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(14, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6(GenericCommandRequestArgs requestArgs, global::ChoppableTree target)
        {
			target.Chop();
        }

        private void ReceiveCommand__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6(CommandData command)
        {
			var target = _3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6_CommandTarget;


            command.Dispose();

			target.Chop();
        }
        private void BakeCommandBinding__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca_CommandTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            var _3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca_localTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"ChoppableTree.PlayChopEffect",
            	"()",
            	SendCommand__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca,
            	__args => ReceiveLocalCommand__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca(__args, _3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca_localTarget),
            	MessageTarget.Other,
            	_3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(13, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca(GenericCommandRequestArgs requestArgs, global::ChoppableTree target)
        {
			target.PlayChopEffect();
        }

        private void ReceiveCommand__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca(CommandData command)
        {
			var target = _3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca_CommandTarget;


            command.Dispose();

			target.PlayChopEffect();
        }
        private void BakeCommandBinding__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404_CommandTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            var _3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404_localTarget = (global::ChoppableTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"ChoppableTree.ChangeState",
            	"(System.Boolean)",
            	SendCommand__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404,
            	__args => ReceiveLocalCommand__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404(__args, _3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404_localTarget),
            	MessageTarget.Other,
            	_3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(12, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);

            command.GetField(0).SetBool(((System.Boolean)requestArgs.Args[0]));

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404(GenericCommandRequestArgs requestArgs, global::ChoppableTree target)
        {
			target.ChangeState((global::System.Boolean)(requestArgs.Args[0]));
        }

        private void ReceiveCommand__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404(CommandData command)
        {
			var target = _3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404_CommandTarget;

            var arg0 = (System.Boolean)(command.GetField(0).GetBool());

            command.Dispose();

			target.ChangeState(arg0);
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                case 14:
                    ReceiveCommand__3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6(command);
                    break;
                case 13:
                    ReceiveCommand__3d92447627afdfc419ceeb6b26251a87_d1abac12daa945619882e28463e3e3ca(command);
                    break;
                case 12:
                    ReceiveCommand__3d92447627afdfc419ceeb6b26251a87_4bd44a0c7fb3400db0d9719709cd4404(command);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_3d92447627afdfc419ceeb6b26251a87 Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_3d92447627afdfc419ceeb6b26251a87>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
