// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_0d09d827e9dc48d48234312ff3610eb4 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_ea22c661324048629b36fc289800b247 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 1;
        public override int FieldIndex => 0;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetQuaternion().ToUnityQuaternion();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetQuaternion(Value.ToCoreQuaternion());
            }
            else
            {
                field.SetQuaternion(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToCoreQuaternion());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_abd6ea830b7b416c8a6dd35eb11f2a4f : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 17;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_59b52bcb476d404a94c7b0a30cfbaf19 : StringBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override uint CoherenceComponentID => 38;
        public override int FieldIndex => 0;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.path); }
            set { CastedUnityComponent.path = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetString();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetString(Value);
            }
            else
            {
                field.SetString(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_cc845b8866124cb082e0181af5e7f681 : IntBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override uint CoherenceComponentID => 38;
        public override int FieldIndex => 1;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.pathDirtyCounter); }
            set { CastedUnityComponent.pathDirtyCounter = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(1);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(1);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_2ef575fde1d84535b83a10a14e8b6cd0 : BoolBinding
    {   
        private global::Grabbable CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Grabbable)UnityComponent;
        }

        public override uint CoherenceComponentID => 37;
        public override int FieldIndex => 0;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingCarried); }
            set { CastedUnityComponent.isBeingCarried = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetBool();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetBool(Value);
            }
            else
            {
                field.SetBool(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_f2d1c22c30b044c8bb3dddc445e2c67a : ReferenceBinding
    {   
        private global::PositionedObject CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::PositionedObject)UnityComponent;
        }

        public override uint CoherenceComponentID => 36;
        public override int FieldIndex => 0;

        public override Entity Value
        {
            get { return coherenceSync.CoherenceBridge.UnityObjectToEntityId((ICoherenceSync)(CastedUnityComponent.objectAnchorSync)); }
            set { CastedUnityComponent.objectAnchorSync = coherenceSync.CoherenceBridge.EntityIdToCoherenceSync(value); }
        }

        protected override (Entity value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetEntity();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetEntity(Value);
            }
            else
            {
                field.SetEntity(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_8d0ae98c8cb2746df8fa6b7fef5ee166 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_8d0ae98c8cb2746df8fa6b7fef5ee166>();
        
        private global::PositionedObject _8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["0d09d827e9dc48d48234312ff3610eb4"] = new Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_0d09d827e9dc48d48234312ff3610eb4(),
			["ea22c661324048629b36fc289800b247"] = new Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_ea22c661324048629b36fc289800b247(),
			["abd6ea830b7b416c8a6dd35eb11f2a4f"] = new Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_abd6ea830b7b416c8a6dd35eb11f2a4f(),
			["59b52bcb476d404a94c7b0a30cfbaf19"] = new Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_59b52bcb476d404a94c7b0a30cfbaf19(),
			["cc845b8866124cb082e0181af5e7f681"] = new Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_cc845b8866124cb082e0181af5e7f681(),
			["2ef575fde1d84535b83a10a14e8b6cd0"] = new Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_2ef575fde1d84535b83a10a14e8b6cd0(),
			["f2d1c22c30b044c8bb3dddc445e2c67a"] = new Binding_8d0ae98c8cb2746df8fa6b7fef5ee166_f2d1c22c30b044c8bb3dddc445e2c67a(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_8d0ae98c8cb2746df8fa6b7fef5ee166()
        {
            bakedCommandBindings.Add("1d97e8b68da1419a9d8bbf2023980031", BakeCommandBinding__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031_CommandTarget = (global::PositionedObject)commandBinding.UnityComponent;
            var _8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031_localTarget = (global::PositionedObject)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"PositionedObject.PlayReappearShaderEffect",
            	"()",
            	SendCommand__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031,
            	__args => ReceiveLocalCommand__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031(__args, _8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031_localTarget),
            	MessageTarget.All,
            	_8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(19, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031(GenericCommandRequestArgs requestArgs, global::PositionedObject target)
        {
			target.PlayReappearShaderEffect();
        }

        private void ReceiveCommand__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031(CommandData command)
        {
			var target = _8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031_CommandTarget;


            command.Dispose();

			target.PlayReappearShaderEffect();
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                case 19:
                    ReceiveCommand__8d0ae98c8cb2746df8fa6b7fef5ee166_1d97e8b68da1419a9d8bbf2023980031(command);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_8d0ae98c8cb2746df8fa6b7fef5ee166 Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_8d0ae98c8cb2746df8fa6b7fef5ee166>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
