// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

using Coherence;
using Coherence.Toolkit;

#if !COHERENCE_COMMAND_EXTENSIONS_DISABLE
[UnityEngine.Scripting.Preserve]
public static class CommandsFor_ChoppableTree
{
    public static bool Chop(this ChoppableTree self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(Chop), target);
    }

    public static bool PlayChopEffect(this ChoppableTree self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayChopEffect), target);
    }

    public static bool ChangeState(this ChoppableTree self, MessageTarget target, System.Boolean toUp)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(ChangeState), target, (typeof(System.Boolean), (object)toUp));
    }
}
#endif

