// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

using Coherence;
using Coherence.Toolkit;

#if !COHERENCE_COMMAND_EXTENSIONS_DISABLE
[UnityEngine.Scripting.Preserve]
public static class CommandsFor_KeeperRobot
{
    public static bool PlayHumSound(this KeeperRobot self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayHumSound), target);
    }

    public static bool PlayVoiceSound(this KeeperRobot self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayVoiceSound), target);
    }

    public static bool PlayConjure(this KeeperRobot self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayConjure), target);
    }

    public static bool PlayAppear(this KeeperRobot self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayAppear), target);
    }
}
#endif

