// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

using Coherence;
using Coherence.Toolkit;

#if !COHERENCE_COMMAND_EXTENSIONS_DISABLE
[UnityEngine.Scripting.Preserve]
public static class CommandsFor_Campfire
{
    public static bool BurnObject(this Campfire self, MessageTarget target, System.String syncConfigID)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(BurnObject), target, (typeof(System.String), (object)syncConfigID));
    }

    public static bool PlayInstantEffects(this Campfire self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayInstantEffects), target);
    }

    public static bool FireDiedDown(this Campfire self, MessageTarget target, System.Int32 oldEffectID, System.Int32 newEffectID)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(FireDiedDown), target, (typeof(System.Int32), (object)oldEffectID), (typeof(System.Int32), (object)newEffectID));
    }

    public static bool FireStateChanged(this Campfire self, MessageTarget target, System.Int32 oldEffectID, System.Int32 newEffectID, System.String syncConfigID)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(FireStateChanged), target, (typeof(System.Int32), (object)oldEffectID), (typeof(System.Int32), (object)newEffectID), (typeof(System.String), (object)syncConfigID));
    }
}
#endif

