// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

using Coherence;
using Coherence.Toolkit;

#if !COHERENCE_COMMAND_EXTENSIONS_DISABLE
[UnityEngine.Scripting.Preserve]
public static class CommandsFor_Emotes
{
    public static bool PlayYesSound(this Emotes self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayYesSound), target);
    }

    public static bool PlayNoSound(this Emotes self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayNoSound), target);
    }

    public static bool PlayHeySound(this Emotes self, MessageTarget target)
    {
        if (!self)
        {
            return false;
        }

        var _sync = self.GetComponentInParent<CoherenceSync>(true);
        if (!_sync)
        {
            return false;
        }

        return _sync.SendCommand(self, nameof(PlayHeySound), target);
    }
}
#endif

