// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Connection;
    using Coherence.Entities;
    using Coherence.Serializer;
    using Coherence.Log;
    using Coherence.SimulationFrame;


    [UnityEngine.Scripting.Preserve]

    public class Definition : IDefinition
    {
        public const string schemaId = "c84903806b884690f25e4085129bea720d2c36cb";
        public const uint InternalWorldPosition = 0;
        public const uint InternalWorldOrientation = 1;
        public const uint InternalLocalUserComponent = 2;
        public const uint InternalWorldPositionQuery = 3;
        public const uint InternalArchetypeComponent = 4;
        public const uint InternalPersistence = 5;
        public const uint InternalConnectedEntity = 6;
        public const uint InternalUniqueID = 7;
        public const uint InternalConnection = 8;
        public const uint InternalConnectionScene = 9;
        public const uint InternalGlobal = 10;
        public const uint InternalGlobalQuery = 11;
        public const uint InternalTag = 12;
        public const uint InternalTagQuery = 13;
        public const uint InternalPreserveChildren = 14;
        public const uint InternalScene = 15;
        public const uint InternalAssetId = 16;
        public const uint InternalGenericScale = 17;
        public const uint Internal_0109999de4f6d45bb8c13493b504dee7_1143969198414876421 = 18;
        public const uint Internal_0109999de4f6d45bb8c13493b504dee7_616379459864002610 = 19;
        public const uint Internal_0109999de4f6d45bb8c13493b504dee7_6732985197249073484 = 20;
        public const uint Internal_0d27e1ad6d8e5ba4abca3216a92298f7_4384992023136877932 = 21;
        public const uint Internal_0d27e1ad6d8e5ba4abca3216a92298f7_7577043058907851794 = 22;
        public const uint Internal_0d27e1ad6d8e5ba4abca3216a92298f7_7947429143224902437 = 23;
        public const uint Internal_3889a458e94666d4784df30d8dd06d7d_6540142254599110064 = 24;
        public const uint Internal_3d92447627afdfc419ceeb6b26251a87_1406947345458511524 = 25;
        public const uint Internal_451e73a8eddd14b2daf891b5ee6c2308_318412099543152777 = 26;
        public const uint Internal_451e73a8eddd14b2daf891b5ee6c2308_5879086033831766519 = 27;
        public const uint Internal_451e73a8eddd14b2daf891b5ee6c2308_6267697520601458368 = 28;
        public const uint Internal_7455a9685d292b843b28465a4faffd05_4295192434143702777 = 29;
        public const uint Internal_7455a9685d292b843b28465a4faffd05_486810980 = 30;
        public const uint Internal_7eef8177eb732314fb850470094a70c9_468635231 = 31;
        public const uint Internal_7eef8177eb732314fb850470094a70c9_468635232 = 32;
        public const uint Internal_89bb435d615753b4f86caa89fd2a5d9d_4071990166734286761 = 33;
        public const uint Internal_89bb435d615753b4f86caa89fd2a5d9d_4607038716989399198 = 34;
        public const uint Internal_89bb435d615753b4f86caa89fd2a5d9d_7643438469673120224 = 35;
        public const uint Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_4384992023136877932 = 36;
        public const uint Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_7577043058907851794 = 37;
        public const uint Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_7947429143224902437 = 38;
        public const uint Internal_91ccee2338d92624a8021fda1c91e47c_1987083777327440787 = 39;
        public const uint Internal_91ccee2338d92624a8021fda1c91e47c_4713251173614319484 = 40;
        public const uint Internal_9ea9c7ad1465c4769a67e80391f1158b_2975753946441600970 = 41;
        public const uint Internal_9ea9c7ad1465c4769a67e80391f1158b_3324184583126450429 = 42;
        public const uint Internal_a857fd6c221f7f04fa9ed500e317642a_4667129514690375174 = 43;
        public const uint Internal_a857fd6c221f7f04fa9ed500e317642a_8551261703447512967 = 44;
        public const uint Internal_c76bd173fbfcfba44982ec0a19f9c897_4384992023136877932 = 45;
        public const uint Internal_c76bd173fbfcfba44982ec0a19f9c897_7577043058907851794 = 46;
        public const uint Internal_c76bd173fbfcfba44982ec0a19f9c897_7947429143224902437 = 47;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_176131441763086322 = 48;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181 = 49;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216 = 50;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408 = 51;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618 = 52;
        public const uint Internal_e74854605b68b435280bc0ac73fef6c1_6806255523165594879 = 53;
        public const uint Internal_e74854605b68b435280bc0ac73fef6c1_831233887725647233 = 54;
        public const uint Internal_e74854605b68b435280bc0ac73fef6c1_929081723536030390 = 55;
        public const uint Internal_ec47cd7906b7749f4853524abf78e799_432812263773753349 = 56;
        public const uint Internal_f446f3c484ae048c4ba11ef7b8642420_4071990166734286761 = 57;
        public const uint Internal_f446f3c484ae048c4ba11ef7b8642420_4607038716989399198 = 58;
        public const uint Internal_f446f3c484ae048c4ba11ef7b8642420_7643438469673120224 = 59;
        public const uint InternalArchetype_3889a458e94666d4784df30d8dd06d7d_WorldPosition_LOD0 = 60;
        public const uint InternalArchetype_3889a458e94666d4784df30d8dd06d7d__3889a458e94666d4784df30d8dd06d7d_6540142254599110064_LOD0 = 61;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0 = 62;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0 = 63;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0 = 64;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618_LOD0 = 65;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181_LOD0 = 66;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408_LOD0 = 67;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_176131441763086322_LOD0 = 68;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216_LOD0 = 69;
        public const uint InternalAuthorityRequest = 0;
        public const uint InternalAuthorityTransfer = 1;
        public const uint InternalQuerySynced = 2;
        public const uint InternalAdoptOrphan = 3;
        public const uint InternalPersistenceReady = 4;
        public const uint InternalSceneIndexChanged = 5;
        public const uint Internal_0109999de4f6d45bb8c13493b504dee7_ad9e635638034d88b0c6dcd8a9c83286 = 6;
        public const uint Internal_0d27e1ad6d8e5ba4abca3216a92298f7_ad9e635638034d88b0c6dcd8a9c83286 = 7;
        public const uint Internal_3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38 = 8;
        public const uint Internal_3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db = 9;
        public const uint Internal_3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391 = 10;
        public const uint Internal_3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4 = 11;
        public const uint Internal_3d92447627afdfc419ceeb6b26251a87_195171a3094b49ce9dc624b38e8a6b09 = 12;
        public const uint Internal_3d92447627afdfc419ceeb6b26251a87_64674b8d4999426fb995493ab95cb6d7 = 13;
        public const uint Internal_3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6 = 14;
        public const uint Internal_451e73a8eddd14b2daf891b5ee6c2308_ad9e635638034d88b0c6dcd8a9c83286 = 15;
        public const uint Internal_7455a9685d292b843b28465a4faffd05_4f5f31474cef489f91936637c9eefcff = 16;
        public const uint Internal_7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187 = 17;
        public const uint Internal_89bb435d615753b4f86caa89fd2a5d9d_ad9e635638034d88b0c6dcd8a9c83286 = 18;
        public const uint Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_ad9e635638034d88b0c6dcd8a9c83286 = 19;
        public const uint Internal_91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9 = 20;
        public const uint Internal_a857fd6c221f7f04fa9ed500e317642a_0f10acf8439d449385dbd33450d1f0fb = 21;
        public const uint Internal_a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4 = 22;
        public const uint Internal_a857fd6c221f7f04fa9ed500e317642a_a08cbf1b7c0b489e9d34a142c88514c8 = 23;
        public const uint Internal_a857fd6c221f7f04fa9ed500e317642a_e584959f421448c0b118bf28bd4867b2 = 24;
        public const uint Internal_a857fd6c221f7f04fa9ed500e317642a_e86b8c2ff539476e96c5792baaad07d6 = 25;
        public const uint Internal_c76bd173fbfcfba44982ec0a19f9c897_ad9e635638034d88b0c6dcd8a9c83286 = 26;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41 = 27;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829 = 28;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6 = 29;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8 = 30;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142 = 31;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5 = 32;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d = 33;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c = 34;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe = 35;
        public const uint Internal_e74854605b68b435280bc0ac73fef6c1_ad9e635638034d88b0c6dcd8a9c83286 = 36;
        public const uint Internal_ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d = 37;
        public const uint Internal_f446f3c484ae048c4ba11ef7b8642420_ad9e635638034d88b0c6dcd8a9c83286 = 38;

        private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>()
        {
            { 0, "WorldPosition" },
            { 1, "WorldOrientation" },
            { 2, "LocalUserComponent" },
            { 3, "WorldPositionQuery" },
            { 4, "ArchetypeComponent" },
            { 5, "Persistence" },
            { 6, "ConnectedEntity" },
            { 7, "UniqueID" },
            { 8, "Connection" },
            { 9, "ConnectionScene" },
            { 10, "Global" },
            { 11, "GlobalQuery" },
            { 12, "Tag" },
            { 13, "TagQuery" },
            { 14, "PreserveChildren" },
            { 15, "Scene" },
            { 16, "AssetId" },
            { 17, "GenericScale" },
            { 18, "_0109999de4f6d45bb8c13493b504dee7_1143969198414876421" },
            { 19, "_0109999de4f6d45bb8c13493b504dee7_616379459864002610" },
            { 20, "_0109999de4f6d45bb8c13493b504dee7_6732985197249073484" },
            { 21, "_0d27e1ad6d8e5ba4abca3216a92298f7_4384992023136877932" },
            { 22, "_0d27e1ad6d8e5ba4abca3216a92298f7_7577043058907851794" },
            { 23, "_0d27e1ad6d8e5ba4abca3216a92298f7_7947429143224902437" },
            { 24, "_3889a458e94666d4784df30d8dd06d7d_6540142254599110064" },
            { 25, "_3d92447627afdfc419ceeb6b26251a87_1406947345458511524" },
            { 26, "_451e73a8eddd14b2daf891b5ee6c2308_318412099543152777" },
            { 27, "_451e73a8eddd14b2daf891b5ee6c2308_5879086033831766519" },
            { 28, "_451e73a8eddd14b2daf891b5ee6c2308_6267697520601458368" },
            { 29, "_7455a9685d292b843b28465a4faffd05_4295192434143702777" },
            { 30, "_7455a9685d292b843b28465a4faffd05_486810980" },
            { 31, "_7eef8177eb732314fb850470094a70c9_468635231" },
            { 32, "_7eef8177eb732314fb850470094a70c9_468635232" },
            { 33, "_89bb435d615753b4f86caa89fd2a5d9d_4071990166734286761" },
            { 34, "_89bb435d615753b4f86caa89fd2a5d9d_4607038716989399198" },
            { 35, "_89bb435d615753b4f86caa89fd2a5d9d_7643438469673120224" },
            { 36, "_8d0ae98c8cb2746df8fa6b7fef5ee166_4384992023136877932" },
            { 37, "_8d0ae98c8cb2746df8fa6b7fef5ee166_7577043058907851794" },
            { 38, "_8d0ae98c8cb2746df8fa6b7fef5ee166_7947429143224902437" },
            { 39, "_91ccee2338d92624a8021fda1c91e47c_1987083777327440787" },
            { 40, "_91ccee2338d92624a8021fda1c91e47c_4713251173614319484" },
            { 41, "_9ea9c7ad1465c4769a67e80391f1158b_2975753946441600970" },
            { 42, "_9ea9c7ad1465c4769a67e80391f1158b_3324184583126450429" },
            { 43, "_a857fd6c221f7f04fa9ed500e317642a_4667129514690375174" },
            { 44, "_a857fd6c221f7f04fa9ed500e317642a_8551261703447512967" },
            { 45, "_c76bd173fbfcfba44982ec0a19f9c897_4384992023136877932" },
            { 46, "_c76bd173fbfcfba44982ec0a19f9c897_7577043058907851794" },
            { 47, "_c76bd173fbfcfba44982ec0a19f9c897_7947429143224902437" },
            { 48, "_cd9bcc1feead9419fac0c5981ce85c23_176131441763086322" },
            { 49, "_cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181" },
            { 50, "_cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216" },
            { 51, "_cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408" },
            { 52, "_cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618" },
            { 53, "_e74854605b68b435280bc0ac73fef6c1_6806255523165594879" },
            { 54, "_e74854605b68b435280bc0ac73fef6c1_831233887725647233" },
            { 55, "_e74854605b68b435280bc0ac73fef6c1_929081723536030390" },
            { 56, "_ec47cd7906b7749f4853524abf78e799_432812263773753349" },
            { 57, "_f446f3c484ae048c4ba11ef7b8642420_4071990166734286761" },
            { 58, "_f446f3c484ae048c4ba11ef7b8642420_4607038716989399198" },
            { 59, "_f446f3c484ae048c4ba11ef7b8642420_7643438469673120224" },
            { 60, "Archetype_3889a458e94666d4784df30d8dd06d7d_WorldPosition_LOD0" },
            { 61, "Archetype_3889a458e94666d4784df30d8dd06d7d__3889a458e94666d4784df30d8dd06d7d_6540142254599110064_LOD0" },
            { 62, "Archetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0" },
            { 63, "Archetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0" },
            { 64, "Archetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0" },
            { 65, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618_LOD0" },
            { 66, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181_LOD0" },
            { 67, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408_LOD0" },
            { 68, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_176131441763086322_LOD0" },
            { 69, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216_LOD0" },
        };

        public static string ComponentNameForTypeId(uint typeId)
        {
            if (componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
            {
                return componentName;
            }
            else
            {
                return "";
            }
        }

        public static readonly Dictionary<uint, MessageTarget> CommandRoutingByType = new Dictionary<uint, MessageTarget>()
        {
            { Definition.InternalAuthorityRequest , MessageTarget.All },
            { Definition.InternalAuthorityTransfer , MessageTarget.All },
            { Definition.InternalQuerySynced , MessageTarget.All },
            { Definition.InternalAdoptOrphan , MessageTarget.All },
            { Definition.InternalPersistenceReady , MessageTarget.All },
            { Definition.InternalSceneIndexChanged , MessageTarget.All },
            { Definition.Internal_0109999de4f6d45bb8c13493b504dee7_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
            { Definition.Internal_0d27e1ad6d8e5ba4abca3216a92298f7_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
            { Definition.Internal_3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38 , MessageTarget.All },
            { Definition.Internal_3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db , MessageTarget.All },
            { Definition.Internal_3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391 , MessageTarget.All },
            { Definition.Internal_3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4 , MessageTarget.AuthorityOnly },
            { Definition.Internal_3d92447627afdfc419ceeb6b26251a87_195171a3094b49ce9dc624b38e8a6b09 , MessageTarget.Other },
            { Definition.Internal_3d92447627afdfc419ceeb6b26251a87_64674b8d4999426fb995493ab95cb6d7 , MessageTarget.Other },
            { Definition.Internal_3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6 , MessageTarget.AuthorityOnly },
            { Definition.Internal_451e73a8eddd14b2daf891b5ee6c2308_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
            { Definition.Internal_7455a9685d292b843b28465a4faffd05_4f5f31474cef489f91936637c9eefcff , MessageTarget.AuthorityOnly },
            { Definition.Internal_7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187 , MessageTarget.AuthorityOnly },
            { Definition.Internal_89bb435d615753b4f86caa89fd2a5d9d_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
            { Definition.Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
            { Definition.Internal_91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9 , MessageTarget.AuthorityOnly },
            { Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_0f10acf8439d449385dbd33450d1f0fb , MessageTarget.All },
            { Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4 , MessageTarget.AuthorityOnly },
            { Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_a08cbf1b7c0b489e9d34a142c88514c8 , MessageTarget.All },
            { Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_e584959f421448c0b118bf28bd4867b2 , MessageTarget.All },
            { Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_e86b8c2ff539476e96c5792baaad07d6 , MessageTarget.All },
            { Definition.Internal_c76bd173fbfcfba44982ec0a19f9c897_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41 , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829 , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6 , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8 , MessageTarget.Other },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142 , MessageTarget.Other },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5 , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe , MessageTarget.Other },
            { Definition.Internal_e74854605b68b435280bc0ac73fef6c1_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
            { Definition.Internal_ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d , MessageTarget.AuthorityOnly },
            { Definition.Internal_f446f3c484ae048c4ba11ef7b8642420_ad9e635638034d88b0c6dcd8a9c83286 , MessageTarget.All },
        };

        public ICoherenceComponentData ReadComponentUpdate(uint componentType, AbsoluteSimulationFrame referenceSimulationFrame,
            IInBitStream bitStream, Logger logger)
        {
            var inProtocolStream = new InProtocolBitStream(bitStream);

            switch (componentType)
            {
                case InternalWorldPosition:
                    return WorldPosition.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldOrientation:
                    return WorldOrientation.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPersistence:
                    return Persistence.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectedEntity:
                    return ConnectedEntity.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalUniqueID:
                    return UniqueID.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnection:
                    return Connection.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectionScene:
                    return ConnectionScene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobal:
                    return Global.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobalQuery:
                    return GlobalQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTag:
                    return Tag.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTagQuery:
                    return TagQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPreserveChildren:
                    return PreserveChildren.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalScene:
                    return Scene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalAssetId:
                    return AssetId.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGenericScale:
                    return GenericScale.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0109999de4f6d45bb8c13493b504dee7_1143969198414876421:
                    return _0109999de4f6d45bb8c13493b504dee7_1143969198414876421.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0109999de4f6d45bb8c13493b504dee7_616379459864002610:
                    return _0109999de4f6d45bb8c13493b504dee7_616379459864002610.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0109999de4f6d45bb8c13493b504dee7_6732985197249073484:
                    return _0109999de4f6d45bb8c13493b504dee7_6732985197249073484.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0d27e1ad6d8e5ba4abca3216a92298f7_4384992023136877932:
                    return _0d27e1ad6d8e5ba4abca3216a92298f7_4384992023136877932.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0d27e1ad6d8e5ba4abca3216a92298f7_7577043058907851794:
                    return _0d27e1ad6d8e5ba4abca3216a92298f7_7577043058907851794.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0d27e1ad6d8e5ba4abca3216a92298f7_7947429143224902437:
                    return _0d27e1ad6d8e5ba4abca3216a92298f7_7947429143224902437.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_3889a458e94666d4784df30d8dd06d7d_6540142254599110064:
                    return _3889a458e94666d4784df30d8dd06d7d_6540142254599110064.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_3d92447627afdfc419ceeb6b26251a87_1406947345458511524:
                    return _3d92447627afdfc419ceeb6b26251a87_1406947345458511524.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_451e73a8eddd14b2daf891b5ee6c2308_318412099543152777:
                    return _451e73a8eddd14b2daf891b5ee6c2308_318412099543152777.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_451e73a8eddd14b2daf891b5ee6c2308_5879086033831766519:
                    return _451e73a8eddd14b2daf891b5ee6c2308_5879086033831766519.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_451e73a8eddd14b2daf891b5ee6c2308_6267697520601458368:
                    return _451e73a8eddd14b2daf891b5ee6c2308_6267697520601458368.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_7455a9685d292b843b28465a4faffd05_4295192434143702777:
                    return _7455a9685d292b843b28465a4faffd05_4295192434143702777.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_7455a9685d292b843b28465a4faffd05_486810980:
                    return _7455a9685d292b843b28465a4faffd05_486810980.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_7eef8177eb732314fb850470094a70c9_468635231:
                    return _7eef8177eb732314fb850470094a70c9_468635231.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_7eef8177eb732314fb850470094a70c9_468635232:
                    return _7eef8177eb732314fb850470094a70c9_468635232.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_89bb435d615753b4f86caa89fd2a5d9d_4071990166734286761:
                    return _89bb435d615753b4f86caa89fd2a5d9d_4071990166734286761.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_89bb435d615753b4f86caa89fd2a5d9d_4607038716989399198:
                    return _89bb435d615753b4f86caa89fd2a5d9d_4607038716989399198.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_89bb435d615753b4f86caa89fd2a5d9d_7643438469673120224:
                    return _89bb435d615753b4f86caa89fd2a5d9d_7643438469673120224.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_4384992023136877932:
                    return _8d0ae98c8cb2746df8fa6b7fef5ee166_4384992023136877932.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_7577043058907851794:
                    return _8d0ae98c8cb2746df8fa6b7fef5ee166_7577043058907851794.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_7947429143224902437:
                    return _8d0ae98c8cb2746df8fa6b7fef5ee166_7947429143224902437.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_91ccee2338d92624a8021fda1c91e47c_1987083777327440787:
                    return _91ccee2338d92624a8021fda1c91e47c_1987083777327440787.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_91ccee2338d92624a8021fda1c91e47c_4713251173614319484:
                    return _91ccee2338d92624a8021fda1c91e47c_4713251173614319484.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_9ea9c7ad1465c4769a67e80391f1158b_2975753946441600970:
                    return _9ea9c7ad1465c4769a67e80391f1158b_2975753946441600970.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_9ea9c7ad1465c4769a67e80391f1158b_3324184583126450429:
                    return _9ea9c7ad1465c4769a67e80391f1158b_3324184583126450429.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a857fd6c221f7f04fa9ed500e317642a_4667129514690375174:
                    return _a857fd6c221f7f04fa9ed500e317642a_4667129514690375174.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a857fd6c221f7f04fa9ed500e317642a_8551261703447512967:
                    return _a857fd6c221f7f04fa9ed500e317642a_8551261703447512967.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_c76bd173fbfcfba44982ec0a19f9c897_4384992023136877932:
                    return _c76bd173fbfcfba44982ec0a19f9c897_4384992023136877932.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_c76bd173fbfcfba44982ec0a19f9c897_7577043058907851794:
                    return _c76bd173fbfcfba44982ec0a19f9c897_7577043058907851794.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_c76bd173fbfcfba44982ec0a19f9c897_7947429143224902437:
                    return _c76bd173fbfcfba44982ec0a19f9c897_7947429143224902437.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_176131441763086322:
                    return _cd9bcc1feead9419fac0c5981ce85c23_176131441763086322.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181:
                    return _cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618:
                    return _cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_e74854605b68b435280bc0ac73fef6c1_6806255523165594879:
                    return _e74854605b68b435280bc0ac73fef6c1_6806255523165594879.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_e74854605b68b435280bc0ac73fef6c1_831233887725647233:
                    return _e74854605b68b435280bc0ac73fef6c1_831233887725647233.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_e74854605b68b435280bc0ac73fef6c1_929081723536030390:
                    return _e74854605b68b435280bc0ac73fef6c1_929081723536030390.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_ec47cd7906b7749f4853524abf78e799_432812263773753349:
                    return _ec47cd7906b7749f4853524abf78e799_432812263773753349.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_f446f3c484ae048c4ba11ef7b8642420_4071990166734286761:
                    return _f446f3c484ae048c4ba11ef7b8642420_4071990166734286761.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_f446f3c484ae048c4ba11ef7b8642420_4607038716989399198:
                    return _f446f3c484ae048c4ba11ef7b8642420_4607038716989399198.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_f446f3c484ae048c4ba11ef7b8642420_7643438469673120224:
                    return _f446f3c484ae048c4ba11ef7b8642420_7643438469673120224.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_3889a458e94666d4784df30d8dd06d7d_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_3889a458e94666d4784df30d8dd06d7d_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_3889a458e94666d4784df30d8dd06d7d__3889a458e94666d4784df30d8dd06d7d_6540142254599110064_LOD0:
                    return _3889a458e94666d4784df30d8dd06d7d_6540142254599110064.DeserializeArchetype_3889a458e94666d4784df30d8dd06d7d__3889a458e94666d4784df30d8dd06d7d_6540142254599110064_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0:
                    return GenericScale.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_176131441763086322_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_176131441763086322.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_176131441763086322_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216_LOD0(referenceSimulationFrame, inProtocolStream);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(componentType),
                        $"Missing serialization implementation for a component: {componentType}");
            }
        }

        public uint WriteComponentUpdate(ICoherenceComponentData data, uint serializeAs, bool isRefSimFrameValid,
            AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream protocolStream, Logger logger)
        {
            switch (serializeAs)
            {
                case InternalWorldPosition:
                    return WorldPosition.Serialize((WorldPosition)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldOrientation:
                    return WorldOrientation.Serialize((WorldOrientation)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Serialize((LocalUserComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Serialize((WorldPositionQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Serialize((ArchetypeComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPersistence:
                    return Persistence.Serialize((Persistence)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectedEntity:
                    return ConnectedEntity.Serialize((ConnectedEntity)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalUniqueID:
                    return UniqueID.Serialize((UniqueID)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnection:
                    return Connection.Serialize((Connection)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectionScene:
                    return ConnectionScene.Serialize((ConnectionScene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobal:
                    return Global.Serialize((Global)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobalQuery:
                    return GlobalQuery.Serialize((GlobalQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTag:
                    return Tag.Serialize((Tag)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTagQuery:
                    return TagQuery.Serialize((TagQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPreserveChildren:
                    return PreserveChildren.Serialize((PreserveChildren)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalScene:
                    return Scene.Serialize((Scene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalAssetId:
                    return AssetId.Serialize((AssetId)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGenericScale:
                    return GenericScale.Serialize((GenericScale)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0109999de4f6d45bb8c13493b504dee7_1143969198414876421:
                    return _0109999de4f6d45bb8c13493b504dee7_1143969198414876421.Serialize((_0109999de4f6d45bb8c13493b504dee7_1143969198414876421)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0109999de4f6d45bb8c13493b504dee7_616379459864002610:
                    return _0109999de4f6d45bb8c13493b504dee7_616379459864002610.Serialize((_0109999de4f6d45bb8c13493b504dee7_616379459864002610)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0109999de4f6d45bb8c13493b504dee7_6732985197249073484:
                    return _0109999de4f6d45bb8c13493b504dee7_6732985197249073484.Serialize((_0109999de4f6d45bb8c13493b504dee7_6732985197249073484)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0d27e1ad6d8e5ba4abca3216a92298f7_4384992023136877932:
                    return _0d27e1ad6d8e5ba4abca3216a92298f7_4384992023136877932.Serialize((_0d27e1ad6d8e5ba4abca3216a92298f7_4384992023136877932)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0d27e1ad6d8e5ba4abca3216a92298f7_7577043058907851794:
                    return _0d27e1ad6d8e5ba4abca3216a92298f7_7577043058907851794.Serialize((_0d27e1ad6d8e5ba4abca3216a92298f7_7577043058907851794)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0d27e1ad6d8e5ba4abca3216a92298f7_7947429143224902437:
                    return _0d27e1ad6d8e5ba4abca3216a92298f7_7947429143224902437.Serialize((_0d27e1ad6d8e5ba4abca3216a92298f7_7947429143224902437)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_3889a458e94666d4784df30d8dd06d7d_6540142254599110064:
                    return _3889a458e94666d4784df30d8dd06d7d_6540142254599110064.Serialize((_3889a458e94666d4784df30d8dd06d7d_6540142254599110064)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_3d92447627afdfc419ceeb6b26251a87_1406947345458511524:
                    return _3d92447627afdfc419ceeb6b26251a87_1406947345458511524.Serialize((_3d92447627afdfc419ceeb6b26251a87_1406947345458511524)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_451e73a8eddd14b2daf891b5ee6c2308_318412099543152777:
                    return _451e73a8eddd14b2daf891b5ee6c2308_318412099543152777.Serialize((_451e73a8eddd14b2daf891b5ee6c2308_318412099543152777)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_451e73a8eddd14b2daf891b5ee6c2308_5879086033831766519:
                    return _451e73a8eddd14b2daf891b5ee6c2308_5879086033831766519.Serialize((_451e73a8eddd14b2daf891b5ee6c2308_5879086033831766519)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_451e73a8eddd14b2daf891b5ee6c2308_6267697520601458368:
                    return _451e73a8eddd14b2daf891b5ee6c2308_6267697520601458368.Serialize((_451e73a8eddd14b2daf891b5ee6c2308_6267697520601458368)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_7455a9685d292b843b28465a4faffd05_4295192434143702777:
                    return _7455a9685d292b843b28465a4faffd05_4295192434143702777.Serialize((_7455a9685d292b843b28465a4faffd05_4295192434143702777)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_7455a9685d292b843b28465a4faffd05_486810980:
                    return _7455a9685d292b843b28465a4faffd05_486810980.Serialize((_7455a9685d292b843b28465a4faffd05_486810980)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_7eef8177eb732314fb850470094a70c9_468635231:
                    return _7eef8177eb732314fb850470094a70c9_468635231.Serialize((_7eef8177eb732314fb850470094a70c9_468635231)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_7eef8177eb732314fb850470094a70c9_468635232:
                    return _7eef8177eb732314fb850470094a70c9_468635232.Serialize((_7eef8177eb732314fb850470094a70c9_468635232)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_89bb435d615753b4f86caa89fd2a5d9d_4071990166734286761:
                    return _89bb435d615753b4f86caa89fd2a5d9d_4071990166734286761.Serialize((_89bb435d615753b4f86caa89fd2a5d9d_4071990166734286761)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_89bb435d615753b4f86caa89fd2a5d9d_4607038716989399198:
                    return _89bb435d615753b4f86caa89fd2a5d9d_4607038716989399198.Serialize((_89bb435d615753b4f86caa89fd2a5d9d_4607038716989399198)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_89bb435d615753b4f86caa89fd2a5d9d_7643438469673120224:
                    return _89bb435d615753b4f86caa89fd2a5d9d_7643438469673120224.Serialize((_89bb435d615753b4f86caa89fd2a5d9d_7643438469673120224)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_4384992023136877932:
                    return _8d0ae98c8cb2746df8fa6b7fef5ee166_4384992023136877932.Serialize((_8d0ae98c8cb2746df8fa6b7fef5ee166_4384992023136877932)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_7577043058907851794:
                    return _8d0ae98c8cb2746df8fa6b7fef5ee166_7577043058907851794.Serialize((_8d0ae98c8cb2746df8fa6b7fef5ee166_7577043058907851794)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_7947429143224902437:
                    return _8d0ae98c8cb2746df8fa6b7fef5ee166_7947429143224902437.Serialize((_8d0ae98c8cb2746df8fa6b7fef5ee166_7947429143224902437)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_91ccee2338d92624a8021fda1c91e47c_1987083777327440787:
                    return _91ccee2338d92624a8021fda1c91e47c_1987083777327440787.Serialize((_91ccee2338d92624a8021fda1c91e47c_1987083777327440787)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_91ccee2338d92624a8021fda1c91e47c_4713251173614319484:
                    return _91ccee2338d92624a8021fda1c91e47c_4713251173614319484.Serialize((_91ccee2338d92624a8021fda1c91e47c_4713251173614319484)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_9ea9c7ad1465c4769a67e80391f1158b_2975753946441600970:
                    return _9ea9c7ad1465c4769a67e80391f1158b_2975753946441600970.Serialize((_9ea9c7ad1465c4769a67e80391f1158b_2975753946441600970)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_9ea9c7ad1465c4769a67e80391f1158b_3324184583126450429:
                    return _9ea9c7ad1465c4769a67e80391f1158b_3324184583126450429.Serialize((_9ea9c7ad1465c4769a67e80391f1158b_3324184583126450429)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a857fd6c221f7f04fa9ed500e317642a_4667129514690375174:
                    return _a857fd6c221f7f04fa9ed500e317642a_4667129514690375174.Serialize((_a857fd6c221f7f04fa9ed500e317642a_4667129514690375174)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a857fd6c221f7f04fa9ed500e317642a_8551261703447512967:
                    return _a857fd6c221f7f04fa9ed500e317642a_8551261703447512967.Serialize((_a857fd6c221f7f04fa9ed500e317642a_8551261703447512967)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_c76bd173fbfcfba44982ec0a19f9c897_4384992023136877932:
                    return _c76bd173fbfcfba44982ec0a19f9c897_4384992023136877932.Serialize((_c76bd173fbfcfba44982ec0a19f9c897_4384992023136877932)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_c76bd173fbfcfba44982ec0a19f9c897_7577043058907851794:
                    return _c76bd173fbfcfba44982ec0a19f9c897_7577043058907851794.Serialize((_c76bd173fbfcfba44982ec0a19f9c897_7577043058907851794)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_c76bd173fbfcfba44982ec0a19f9c897_7947429143224902437:
                    return _c76bd173fbfcfba44982ec0a19f9c897_7947429143224902437.Serialize((_c76bd173fbfcfba44982ec0a19f9c897_7947429143224902437)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_176131441763086322:
                    return _cd9bcc1feead9419fac0c5981ce85c23_176131441763086322.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_176131441763086322)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181:
                    return _cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_3184128103638100181)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_4874302885197676216)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_4998465150839130408)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618:
                    return _cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_8520998716179763618)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_e74854605b68b435280bc0ac73fef6c1_6806255523165594879:
                    return _e74854605b68b435280bc0ac73fef6c1_6806255523165594879.Serialize((_e74854605b68b435280bc0ac73fef6c1_6806255523165594879)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_e74854605b68b435280bc0ac73fef6c1_831233887725647233:
                    return _e74854605b68b435280bc0ac73fef6c1_831233887725647233.Serialize((_e74854605b68b435280bc0ac73fef6c1_831233887725647233)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_e74854605b68b435280bc0ac73fef6c1_929081723536030390:
                    return _e74854605b68b435280bc0ac73fef6c1_929081723536030390.Serialize((_e74854605b68b435280bc0ac73fef6c1_929081723536030390)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_ec47cd7906b7749f4853524abf78e799_432812263773753349:
                    return _ec47cd7906b7749f4853524abf78e799_432812263773753349.Serialize((_ec47cd7906b7749f4853524abf78e799_432812263773753349)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_f446f3c484ae048c4ba11ef7b8642420_4071990166734286761:
                    return _f446f3c484ae048c4ba11ef7b8642420_4071990166734286761.Serialize((_f446f3c484ae048c4ba11ef7b8642420_4071990166734286761)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_f446f3c484ae048c4ba11ef7b8642420_4607038716989399198:
                    return _f446f3c484ae048c4ba11ef7b8642420_4607038716989399198.Serialize((_f446f3c484ae048c4ba11ef7b8642420_4607038716989399198)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_f446f3c484ae048c4ba11ef7b8642420_7643438469673120224:
                    return _f446f3c484ae048c4ba11ef7b8642420_7643438469673120224.Serialize((_f446f3c484ae048c4ba11ef7b8642420_7643438469673120224)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingComponentImplementation, ("component", data.GetComponentType()));
                    return 0;
            }
        }

        private IEntityCommand ReadCommand(uint commandType, Entity entity, MessageTarget target, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    return AuthorityRequest.Deserialize(bitStream, entity, target);
                case Definition.InternalAuthorityTransfer:
                    return AuthorityTransfer.Deserialize(bitStream, entity, target);
                case Definition.InternalQuerySynced:
                    return QuerySynced.Deserialize(bitStream, entity, target);
                case Definition.InternalAdoptOrphan:
                    return AdoptOrphan.Deserialize(bitStream, entity, target);
                case Definition.InternalPersistenceReady:
                    return PersistenceReady.Deserialize(bitStream, entity, target);
                case Definition.InternalSceneIndexChanged:
                    return SceneIndexChanged.Deserialize(bitStream, entity, target);
                case Definition.Internal_0109999de4f6d45bb8c13493b504dee7_ad9e635638034d88b0c6dcd8a9c83286:
                    return _0109999de4f6d45bb8c13493b504dee7_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                case Definition.Internal_0d27e1ad6d8e5ba4abca3216a92298f7_ad9e635638034d88b0c6dcd8a9c83286:
                    return _0d27e1ad6d8e5ba4abca3216a92298f7_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38:
                    return _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38.Deserialize(bitStream, entity, target);
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db:
                    return _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db.Deserialize(bitStream, entity, target);
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391:
                    return _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391.Deserialize(bitStream, entity, target);
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4:
                    return _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4.Deserialize(bitStream, entity, target);
                case Definition.Internal_3d92447627afdfc419ceeb6b26251a87_195171a3094b49ce9dc624b38e8a6b09:
                    return _3d92447627afdfc419ceeb6b26251a87_195171a3094b49ce9dc624b38e8a6b09.Deserialize(bitStream, entity, target);
                case Definition.Internal_3d92447627afdfc419ceeb6b26251a87_64674b8d4999426fb995493ab95cb6d7:
                    return _3d92447627afdfc419ceeb6b26251a87_64674b8d4999426fb995493ab95cb6d7.Deserialize(bitStream, entity, target);
                case Definition.Internal_3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6:
                    return _3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6.Deserialize(bitStream, entity, target);
                case Definition.Internal_451e73a8eddd14b2daf891b5ee6c2308_ad9e635638034d88b0c6dcd8a9c83286:
                    return _451e73a8eddd14b2daf891b5ee6c2308_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                case Definition.Internal_7455a9685d292b843b28465a4faffd05_4f5f31474cef489f91936637c9eefcff:
                    return _7455a9685d292b843b28465a4faffd05_4f5f31474cef489f91936637c9eefcff.Deserialize(bitStream, entity, target);
                case Definition.Internal_7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187:
                    return _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187.Deserialize(bitStream, entity, target);
                case Definition.Internal_89bb435d615753b4f86caa89fd2a5d9d_ad9e635638034d88b0c6dcd8a9c83286:
                    return _89bb435d615753b4f86caa89fd2a5d9d_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                case Definition.Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_ad9e635638034d88b0c6dcd8a9c83286:
                    return _8d0ae98c8cb2746df8fa6b7fef5ee166_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                case Definition.Internal_91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9:
                    return _91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9.Deserialize(bitStream, entity, target);
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_0f10acf8439d449385dbd33450d1f0fb:
                    return _a857fd6c221f7f04fa9ed500e317642a_0f10acf8439d449385dbd33450d1f0fb.Deserialize(bitStream, entity, target);
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4:
                    return _a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4.Deserialize(bitStream, entity, target);
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_a08cbf1b7c0b489e9d34a142c88514c8:
                    return _a857fd6c221f7f04fa9ed500e317642a_a08cbf1b7c0b489e9d34a142c88514c8.Deserialize(bitStream, entity, target);
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_e584959f421448c0b118bf28bd4867b2:
                    return _a857fd6c221f7f04fa9ed500e317642a_e584959f421448c0b118bf28bd4867b2.Deserialize(bitStream, entity, target);
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_e86b8c2ff539476e96c5792baaad07d6:
                    return _a857fd6c221f7f04fa9ed500e317642a_e86b8c2ff539476e96c5792baaad07d6.Deserialize(bitStream, entity, target);
                case Definition.Internal_c76bd173fbfcfba44982ec0a19f9c897_ad9e635638034d88b0c6dcd8a9c83286:
                    return _c76bd173fbfcfba44982ec0a19f9c897_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41:
                    return _cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829:
                    return _cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6:
                    return _cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8:
                    return _cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142:
                    return _cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5:
                    return _cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d:
                    return _cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c:
                    return _cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe:
                    return _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe.Deserialize(bitStream, entity, target);
                case Definition.Internal_e74854605b68b435280bc0ac73fef6c1_ad9e635638034d88b0c6dcd8a9c83286:
                    return _e74854605b68b435280bc0ac73fef6c1_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                case Definition.Internal_ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d:
                    return _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d.Deserialize(bitStream, entity, target);
                case Definition.Internal_f446f3c484ae048c4ba11ef7b8642420_ad9e635638034d88b0c6dcd8a9c83286:
                    return _f446f3c484ae048c4ba11ef7b8642420_ad9e635638034d88b0c6dcd8a9c83286.Deserialize(bitStream, entity, target);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(commandType),
                        $"Missing serialization implementation for a command: {commandType}");
            }
        }

        private IEntityInput ReadInput(uint inputType, Entity entity, long frame, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (inputType)
            {
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(inputType),
                        $"Missing serialization implementation for an input: {inputType}");
            }
        }

        public IEntityCommand[]	ReadCommands(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var commandData = new IEntityCommand[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
                var entityID = DeserializerTools.DeserializeEntity(bitStream);
                var messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
                var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
                var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
                commandData[i] = ReadCommand(componentType, entityID, messageTarget, inBitStream, logger);
            }

            return commandData;
        }

        public IEntityInput[] ReadInputs(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var inputData = new IEntityInput[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
                var entityID = DeserializerTools.DeserializeEntity(bitStream);
                var routing = DeserializerTools.DeserializeMessageTarget(bitStream);
                var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
                var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
                var frame = (long)bitStream.ReadUint64();
                var input = ReadInput(componentType, entityID, frame, inBitStream, logger);
                input.Routing = routing;
                inputData[i] = input;
            }

            return inputData;
        }

        public IEntityCommand ReadCommand(IInBitStream bitStream, Logger logger)
        {
            var entityID = DeserializerTools.DeserializeEntity(bitStream);
            var messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
            var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
            var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);

            return ReadCommand(componentType, entityID, messageTarget, inBitStream, logger);
        }

        public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
                    break;
                case Definition.InternalAuthorityTransfer:
                    AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
                    break;
                case Definition.InternalQuerySynced:
                    QuerySynced.Serialize((QuerySynced)data, bitStream);
                    break;
                case Definition.InternalAdoptOrphan:
                    AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
                    break;
                case Definition.InternalPersistenceReady:
                    PersistenceReady.Serialize((PersistenceReady)data, bitStream);
                    break;
                case Definition.InternalSceneIndexChanged:
                    SceneIndexChanged.Serialize((SceneIndexChanged)data, bitStream);
                    break;
                case Definition.Internal_0109999de4f6d45bb8c13493b504dee7_ad9e635638034d88b0c6dcd8a9c83286:
                    _0109999de4f6d45bb8c13493b504dee7_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_0109999de4f6d45bb8c13493b504dee7_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                case Definition.Internal_0d27e1ad6d8e5ba4abca3216a92298f7_ad9e635638034d88b0c6dcd8a9c83286:
                    _0d27e1ad6d8e5ba4abca3216a92298f7_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_0d27e1ad6d8e5ba4abca3216a92298f7_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38:
                    _3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38.Serialize((_3889a458e94666d4784df30d8dd06d7d_3664e59fd3cd4dd28175902369f5bb38)data, bitStream);
                    break;
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db:
                    _3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db.Serialize((_3889a458e94666d4784df30d8dd06d7d_3738e04300d846dfa774ba252d8208db)data, bitStream);
                    break;
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391:
                    _3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391.Serialize((_3889a458e94666d4784df30d8dd06d7d_df8fe4d8a6104b7ab780e439afba5391)data, bitStream);
                    break;
                case Definition.Internal_3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4:
                    _3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4.Serialize((_3889a458e94666d4784df30d8dd06d7d_f8f688eb08cb493facb6d766417377d4)data, bitStream);
                    break;
                case Definition.Internal_3d92447627afdfc419ceeb6b26251a87_195171a3094b49ce9dc624b38e8a6b09:
                    _3d92447627afdfc419ceeb6b26251a87_195171a3094b49ce9dc624b38e8a6b09.Serialize((_3d92447627afdfc419ceeb6b26251a87_195171a3094b49ce9dc624b38e8a6b09)data, bitStream);
                    break;
                case Definition.Internal_3d92447627afdfc419ceeb6b26251a87_64674b8d4999426fb995493ab95cb6d7:
                    _3d92447627afdfc419ceeb6b26251a87_64674b8d4999426fb995493ab95cb6d7.Serialize((_3d92447627afdfc419ceeb6b26251a87_64674b8d4999426fb995493ab95cb6d7)data, bitStream);
                    break;
                case Definition.Internal_3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6:
                    _3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6.Serialize((_3d92447627afdfc419ceeb6b26251a87_e5df7db2535f410690edf553148f2ac6)data, bitStream);
                    break;
                case Definition.Internal_451e73a8eddd14b2daf891b5ee6c2308_ad9e635638034d88b0c6dcd8a9c83286:
                    _451e73a8eddd14b2daf891b5ee6c2308_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_451e73a8eddd14b2daf891b5ee6c2308_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                case Definition.Internal_7455a9685d292b843b28465a4faffd05_4f5f31474cef489f91936637c9eefcff:
                    _7455a9685d292b843b28465a4faffd05_4f5f31474cef489f91936637c9eefcff.Serialize((_7455a9685d292b843b28465a4faffd05_4f5f31474cef489f91936637c9eefcff)data, bitStream);
                    break;
                case Definition.Internal_7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187:
                    _7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187.Serialize((_7eef8177eb732314fb850470094a70c9_510b1c05cf0249e68fbcff362acff187)data, bitStream);
                    break;
                case Definition.Internal_89bb435d615753b4f86caa89fd2a5d9d_ad9e635638034d88b0c6dcd8a9c83286:
                    _89bb435d615753b4f86caa89fd2a5d9d_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_89bb435d615753b4f86caa89fd2a5d9d_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                case Definition.Internal_8d0ae98c8cb2746df8fa6b7fef5ee166_ad9e635638034d88b0c6dcd8a9c83286:
                    _8d0ae98c8cb2746df8fa6b7fef5ee166_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_8d0ae98c8cb2746df8fa6b7fef5ee166_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                case Definition.Internal_91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9:
                    _91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9.Serialize((_91ccee2338d92624a8021fda1c91e47c_da4067b1fcd34e8a93ae914a3b0df2f9)data, bitStream);
                    break;
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_0f10acf8439d449385dbd33450d1f0fb:
                    _a857fd6c221f7f04fa9ed500e317642a_0f10acf8439d449385dbd33450d1f0fb.Serialize((_a857fd6c221f7f04fa9ed500e317642a_0f10acf8439d449385dbd33450d1f0fb)data, bitStream);
                    break;
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4:
                    _a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4.Serialize((_a857fd6c221f7f04fa9ed500e317642a_7f3e0b9e3ab247f68ebb0067b5b4b6c4)data, bitStream);
                    break;
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_a08cbf1b7c0b489e9d34a142c88514c8:
                    _a857fd6c221f7f04fa9ed500e317642a_a08cbf1b7c0b489e9d34a142c88514c8.Serialize((_a857fd6c221f7f04fa9ed500e317642a_a08cbf1b7c0b489e9d34a142c88514c8)data, bitStream);
                    break;
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_e584959f421448c0b118bf28bd4867b2:
                    _a857fd6c221f7f04fa9ed500e317642a_e584959f421448c0b118bf28bd4867b2.Serialize((_a857fd6c221f7f04fa9ed500e317642a_e584959f421448c0b118bf28bd4867b2)data, bitStream);
                    break;
                case Definition.Internal_a857fd6c221f7f04fa9ed500e317642a_e86b8c2ff539476e96c5792baaad07d6:
                    _a857fd6c221f7f04fa9ed500e317642a_e86b8c2ff539476e96c5792baaad07d6.Serialize((_a857fd6c221f7f04fa9ed500e317642a_e86b8c2ff539476e96c5792baaad07d6)data, bitStream);
                    break;
                case Definition.Internal_c76bd173fbfcfba44982ec0a19f9c897_ad9e635638034d88b0c6dcd8a9c83286:
                    _c76bd173fbfcfba44982ec0a19f9c897_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_c76bd173fbfcfba44982ec0a19f9c897_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41:
                    _cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_2306915e22844eadbded8e81dad23c41)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829:
                    _cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_344741bcfef14e43909a3d3fe59aa829)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6:
                    _cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_3f725e0b03bc47c6b9a9e726699545a6)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8:
                    _cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_9072e96068c94ef9a783ea24d7448bf8)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142:
                    _cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_9b336114382d4c8e917671bfe4a6a142)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5:
                    _cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_a44176edbb6f4de88cf611e02b9b81a5)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d:
                    _cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_a6362094f44f4918a0b4a6b21f19b61d)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c:
                    _cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_c6cd65f2d33547e7800e9cd24ce9a96c)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe:
                    _cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_d80a9015b8844731b2e04870faa56abe)data, bitStream);
                    break;
                case Definition.Internal_e74854605b68b435280bc0ac73fef6c1_ad9e635638034d88b0c6dcd8a9c83286:
                    _e74854605b68b435280bc0ac73fef6c1_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_e74854605b68b435280bc0ac73fef6c1_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                case Definition.Internal_ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d:
                    _ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d.Serialize((_ec47cd7906b7749f4853524abf78e799_d9e25df655c0450f92da43abe92a930d)data, bitStream);
                    break;
                case Definition.Internal_f446f3c484ae048c4ba11ef7b8642420_ad9e635638034d88b0c6dcd8a9c83286:
                    _f446f3c484ae048c4ba11ef7b8642420_ad9e635638034d88b0c6dcd8a9c83286.Serialize((_f446f3c484ae048c4ba11ef7b8642420_ad9e635638034d88b0c6dcd8a9c83286)data, bitStream);
                    break;
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingCommandImplementation, ("command", commandType));
                    break;
            }
        }

        public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
        {
            var inputData = (InputData)data;
            bitStream.WriteLong(inputData.Frame);

            switch (inputType)
            {
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingInputImplementation, ("input", inputType));
                    break;
            }
        }

        public IEntityCommand CreateAuthorityRequest(Entity entity, ClientID requester, AuthorityType authType)
        {
            return new AuthorityRequest(entity, (uint)requester, (int)authType);
        }

        public IEntityCommand CreateAdoptOrphanCommand()
        {
            return new AdoptOrphan();
        }

        public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand,
            out ClientID requester, out AuthorityType authType)
        {
            if (entityCommand is AuthorityRequest request)
            {
                requester = (ClientID)request.requester;
                authType = (AuthorityType)request.authorityType;

                return true;
            }

            requester = default;
            authType = default;

            return false;
        }

        public IEntityCommand CreateAuthorityTransfer(Entity entity, ClientID newAuthority, bool accepted, AuthorityType authType)
        {
            return new AuthorityTransfer(entity, (uint)newAuthority, accepted, (int)authType);
        }

        public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
            out bool transferAccepted, out AuthorityType authType)
        {
            if (entityCommand is AuthorityTransfer transfer)
            {
                newAuthority = (ClientID)transfer.newAuthority;
                transferAccepted = transfer.accepted;
                authType = (AuthorityType)transfer.authorityType;

                return true;
            }

            newAuthority = default;
            transferAccepted = default;
            authType = default;

            return false;
        }

        public ICoherenceComponentData GeneratePersistenceData()
        {
            var persistence = new Persistence();

            return persistence;
        }

        public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid, AbsoluteSimulationFrame simFrame)
        {
            var uniqueID = new UniqueID();
            uniqueID.uuid = uuid;
            uniqueID.uuidSimulationFrame = simFrame;
            uniqueID.FieldsMask = 0b1;

            return uniqueID;
        }

        public ICoherenceComponentData CreateGlobalComponent()
        {
            return new Global();
        }

        public ICoherenceComponentData GenerateGlobalQueryComponent()
        {
            return new GlobalQuery();
        }

        public string ExtractCoherenceUUID(ICoherenceComponentData data)
        {
            var uniqueID = (UniqueID)data;
            return uniqueID.uuid;
        }

        public bool IsConnectedEntity(ICoherenceComponentData data)
        {
            return data.GetComponentType() == Definition.InternalConnectedEntity;
        }

        public Entity ExtractConnectedEntityID(ICoherenceComponentData data)
        {
            var connectedEntity = (ConnectedEntity)data;

            return connectedEntity.value;
        }

        public string ExtractCoherenceTag(ICoherenceComponentData data)
        {
            var tag = (Tag)data;
            return tag.tag;
        }

        public bool TryGetSceneIndexChangedCommand(IEntityCommand entityCommand, out int sceneIndex)
        {
            if (entityCommand is SceneIndexChanged changed)
            {
                sceneIndex = (int)changed.sceneIndex;

                return true;
            }

            sceneIndex = default;

            return false;
        }

        public IEntityCommand CreateSceneIndexChangedCommand(Entity entity, int sceneIndex)
        {
            return new SceneIndexChanged(entity, sceneIndex);
        }

        public bool IsSendOrderedComponent(uint componentID)
        {
            switch(componentID)
            {
                case 6:
                    return true;
                default:
                    return false;
            }
        }
}


}
